### ISSUE TITLE
Strange scan results

### ISSUE THREAD

**Issue by electron1948** [dave-theunsub/clamtk#101]
New to ClamTK, installed yesterday and been running scans. Everything looks good except for this part of the report:

![image](https://user-images.githubusercontent.com/41150264/42628080-e1dea298-85c6-11e8-9e64-1ebdaa82bf07.png)

How can a file with no location and no name be scanned?
I'm not worried just puzzled and would be happy if somebody could explain.  :-)

**Comment by dave-theunsub** [comment]
Hi,

That does look strange. This probably means you don't have information on what was scanned, huh?  Also, I thought I had been skipping the gvfs directories... weird.  I'll have to check that out.

Anyway, can you open up a terminal window and type "clamtk" (no quotes)?  Run the same scan again, and see if there are any error messages or anything that pops up in the terminal window.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
Hi, closing for now. Please open a new issue if you have further questions.
