### ISSUE TITLE
Newly downloaded, new to Linux, wth am I doing?

### ISSUE THREAD

**Issue by mondell2** [dave-theunsub/clamtk#103]
Hi there. Recently switched to Ubuntu from Windows. Paranoid about not having anti-virus. Before I downloaded Clam TK, I read a review that said to download Clam AV, first, so I did. My understanding of Clam Tk is that it gives a user friendly look to Clam AV? Well, when I click on Clam TK nothing happens. So...I think it's not working? Idk. Help?

**Comment by dave-theunsub** [comment]
Hi,

Did you try double clicking the icons? You can change this in the settings.

Sep 14, 2018, 6:42 PM by notifications@github.com:

**Comment by mondell2** [comment]
Yes? That's generally the first thing I do when I try to open a program. Am
I missing something with your question?

**Comment by dave-theunsub** [comment]
Hi,

For next time, installing clamtk should automatically install clamav as a dependency.

Can you open a terminal window? Type "clamtk" (no quotes) and let me know if anything shows up in window.

Thanks,
Dave M

**Comment by dave-theunsub** [comment]
Closing for now. Please open a new issue if you have further questions.
