### ISSUE TITLE
On opening Clamtk, it reports an update is available even when it is up to date

### ISSUE THREAD

**Issue by Kesetyan** [dave-theunsub/clamtk#104]
I am using Ubuntu 18.04

When I click the panel icon to open Clamtk, the gui always shows that an update is available even when the program is up to date.  I run the updater and when there is no new update, the signature code number remains the same and the "An update is available" message disappears".  After closing the gui and re-opening it, the "An update is available" message reappears.  When an update is actually available and I run the updater, the update process is shown and the new signature code number is shown but after closing the gui and re-opening it, the "An update is available" message reappears again.

**Comment by dave-theunsub** [comment]
Hi,
You're referring to signature updates, right? If so, there have been situations where one update server is behind. Has this been going on for awhile or just recently?
Also, try opening a terminal window. Type "clamtk" (no quotes), and as you run it, see if any error messages show up in the terminal window.

**Comment by Kesetyan** [comment]
Hi Dave,
Thanks for your very quick response.

Yes, I did mean signature updates - I should have made that clear, sorry.

I've only been running my Ubuntu desktop for a few weeks and am getting to grips with a new situation for me - however I don't think the problem was there when I first installed ClamAV and ClamTK.  I followed your advice and typed "clamtk" in the terminal and got the following:
Gtk-Message **: Failed to load module "canberra-gtk-module" at /usr/lib/x86_64-linux-gnu/perl5/5.26/Gtk2.pm line 126. There is some sort of corruption I guess - I hope this means something to you and that you can help. Thanks.

**Comment by dave-theunsub** [comment]
Hi,

Ok, let's try this then: Open a terminal window (or reuse current one) and type:

sudo apt-get install libcanberra-gtk-module

That should at least do away with the message that showed up.

As far as the update issue, can you wait a day or two and see if it is solved? Like I said, it's usually just waiting for mirrors to catch up. Post back and we'll go from there.

**Comment by Kesetyan** [comment]
Hi Dave,
I'm very impressed with the speed of feedback - thanks.

I installed the libcanberra-gtk-module as advised and now typing "clamtk" into the terminal does open the program.  I will wait for a few days and report back.  In all other respects ClamTK appears to working correctly.  

It's a new learning experience for me and, at 77, I am a bit long in the tooth for taking on board  such things but I am getting to grips with both Ubuntu and ClamAv with ClamTK at least as far as to do what I can do in Windows 7 - when Microsoft support ceases for Windows 7, in about 14 months time, I shall disconnect my Windows 7 system from the internet and rely on my Ubuntu desktop for on-line activity.

I'll be in touch, thanks for your help, I feel very reassured that you are there.

**Comment by dave-theunsub** [comment]
Hi,

I'm closing this out for now. Feel free to start up new threads when you want to.  Good luck!
