### ISSUE TITLE
Scanning folder does nothing on Ubuntu 16.04

### ISSUE THREAD

**Issue by blOwf1sh** [dave-theunsub/clamtk#106]
Hi,
Ubuntu 16.04 MATE, clamtk 5.20.
I try to scan a folder, but the result is always:
Nothing checked, nothing found - see screenshot (no, sorry, upload doesn`t work here...)
The folder (named "viren" ;-) is full of strange e-mail attachments. If I check them one by one, a lot of them are suspicious.
Thank you,
best regards 
BF

Oops, changing the folder name makes clamtk work! 
Attaching log doesn't work either, so I paste it here...
.........................................................................

ClamTk, v5.20
Sat Nov 17 16:54:25 2018
ClamAV-Signaturen: 6720021
Untersuchte Verzeichnisse:

0 wahrscheinlich infizierte Bedrohungen gefunden (0 Dateien untersucht).

Keine Bedrohungen gefunden.
---------------------------------------------

ClamTk, v5.20
Sat Nov 17 16:55:33 2018
ClamAV-Signaturen: 6720021
Untersuchte Verzeichnisse:

0 wahrscheinlich infizierte Bedrohungen gefunden (0 Dateien untersucht).

Keine Bedrohungen gefunden.
---------------------------------------------

ClamTk, v5.20
Sat Nov 17 16:57:07 2018
ClamAV-Signaturen: 6720021
Untersuchte Verzeichnisse:
/home/*****/viren

1 wahrscheinlich infizierte Bedrohung gefunden (1 Datei untersucht).

/home/*****/viren/Rechnung.zip      Win.Malware.Gamarue-484     
--------------------------------------------------------------------

ClamTk, v5.20
Sat Nov 17 17:18:07 2018
ClamAV-Signaturen: 6720021
Untersuchte Verzeichnisse:

0 wahrscheinlich infizierte Bedrohungen gefunden (0 Dateien untersucht).

Keine Bedrohungen gefunden.
---------------------------------------------

ClamTk, v5.20
Sat Nov 17 17:48:44 2018
ClamAV-Signaturen: 6720021
Untersuchte Verzeichnisse:
/home/*****/irre

11 wahrscheinlich infizierte Bedrohungen gefunden (19 Dateien untersucht).

/home/*****/irre/Ihre-Rechnung.zip                                                                              Win.Trojan.Gamarue-294                            
/home/*****/irre/Ihre-Rechnung-virus.exe                                                                        PUA.Win.Downloader.Soft32downloader-6691270-0     
/home/*****/irre/07.09.2017.zip                                                                                 Win.Trojan.Tofsee-6345150-0                       
/home/*****/irre/Rechnung-APM638865518-10.doc                                                                   Doc.Malware.Generic-6749590-0                     
/home/*****/irre/Streming Mahnung ***** ****** von Rechtsanwaltsgesellschaft Krause & Prof. Dr. Ludwig GbR.zip      Win.Dropper.Nymaim-6681620-0                      
/home/*****/irre/Meinfoto.jpg.zip                                                                               PUA.Win.Downloader.Soft32downloader-6691270-0     
/home/*****/irre/Rechnung.zip                                                                                   PUA.Win.Downloader.Soft32downloader-6691270-0     
/home/*****/irre/Ihre-Rechnung.exe                                                                              PUA.Win.Downloader.Soft32downloader-6691270-0     
/home/*****/irre/rechnung.zip                                                                                   Archive.Filetype.DualExtJS-6168221-2              
/home/*****/irre/rechnung.zip                                                                                   Archive.Filetype.DualExtJS-6168221-2              
/home/*****/irre/Meinfoto.jpg.exe                                                                               PUA.Win.Downloader.Soft32downloader-6691270-0     
----------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by dave-theunsub** [comment]
Hi,

So everything is working for you now?  Also, you shouldn't have to change the folder name for it to work. Can you open a terminal window and type "echo $LANG" and hit enter?

Thanks,
Dave M

**Comment by blOwf1sh** [comment]
Am 18.11.18 um 14:42 schrieb Dave M:
> Hi,
> 
> So everything is working for you now?  Also, you shouldn't have to change the folder name for it to work. Can you open a terminal window and type "echo $LANG" and hit enter?
> 
> Thanks,
> Dave M

Hi Dave,

> echo $LANG
de_DE.UTF-8

It's really strange, the folder name "viren" seems to stop the antivir scan.
I change the name back to "viren", result like reported.
Changed it back to something else - and it works.

Regards,
BF

**Comment by dave-theunsub** [comment]
BF,

Is that directory in the Whitelist (Ausnahmen) by chance?

Thanks,
Dave M

**Comment by blOwf1sh** [comment]
Yes, it IS - sorry...
Thanks for your patience,
BF

Am 18. November 2018 15:42:42 MEZ schrieb Dave M <notifications@github.com>:

**Comment by dave-theunsub** [comment]
Ah, okay! No need to apologize.

I'll close this out for now. If you have any other issues/questions, please open a new ticket.

Thanks,
Dave M
