### ISSUE TITLE
Application hangs without Internet access

### ISSUE THREAD

**Issue by apas-iut** [dave-theunsub/clamtk#107]
I've just installed clamtk-5.26-1.el7.noarch.rpm on Centos7.4 machine which does not have Internet access and updated antivirus database from local mirror.

`clamscan` works fine but when I try to run `clamtk` it hangs for 5 minutes.
Debug with `strace clamtk` shows that application tries to connect to 18.234.32.157:443 and only after timeout error application starts.
```
connect(3, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("18.234.32.157")}
```

**Comment by dave-theunsub** [comment]
Hi,

Try this: open a text editor, and use it to open /home/you/.clamtk/prefs . (Obviously replace you with your name :). Anyway, change the line GUICheck=1 to GUICheck=0. See if that gets it going.

Thanks,
Dave M

**Comment by apas-iut** [comment]
That helped! Thank you Dave!
