### ISSUE TITLE
File scanned: 0

### ISSUE THREAD

**Issue by antmak** [dave-theunsub/clamtk#108]
Sometimes when I start scanning from the ClamTk or ClamGnome, it reports me "File scanned: 0"

While 'clamscan' works fine.

It could be solved by run `rm -rf ~/.clamtk/`

It seems, that it appears on the fresh installation  of clamav and clamtk

It seems, that it is related to 
```
# freshclam
ClamAV update process started at Mon Dec 17 13:04:51 2018
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.100.2 Recommended version: 0.101.0
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
```
(freshclam returns '1' in this case)

**Comment by dave-theunsub** [comment]
@antmak Are you trying to scan a directory? If so, please ensure recursive scanning is enabled.

**Comment by antmak** [comment]
Both files and dirs. After "rm -rf ~/.clamtk/" it started working.

**Comment by dave-theunsub** [comment]
Closing for now as it seems to be working.
