### ISSUE TITLE
ClamTk (6.0) easy to crash just when the virus scanner will start

### ISSUE THREAD

**Issue by antecblue** [dave-theunsub/clamtk#109]
ClamTk (6) Sets "nautilus" to automatically display hidden files when scanning. ClamTk (6) Also easy to crash just when the virus scanner will start. My system is Ubuntu 18.04.2
I also have the Clamtk-gnome extension installed.

**Comment by dave-theunsub** [comment]
Hi,

Thanks for reporting. Can you give some more details? When does this happen - e.g., right-click on a folder within Files or something? Does it happen all the time?

Also, please try this:
1. open a terminal window
2. type "nautilus" (<- I think)
3. now attempt the same scan.
4. if error messages come up in the terminal window, please post them here.

Thanks,
Dave M

**Comment by antecblue** [comment]
ClamTk has only crashed 5 times and it was just after I installed it, it no longer crashes. Unfortunately, I cannot reproduce the crashes. This wrote the terminal at the start of ClamTK Virus search of directory:

```
$ clamtk
Gtk-Message: 13:27:43.488: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by dave-theunsub** [comment]
Ok, thanks for the update. I'll close this for now. Feel free to open a new one if it happens again.

Thanks,
Dave M
