### ISSUE TITLE
Error Installing clamtk on CENTOS 7

### ISSUE THREAD

**Issue by cham2019** [dave-theunsub/clamtk#110]
Hi, 

I downloaded this version for my CENTOS 7 server:
https://bitbucket.org/davem_/clamtk-gtk3/downloads/clamtk-6.00-1.el7.noarch.rpm
I received some dependencies errors which I already took care of.  So, after installing all dependencies, I tried again, and still remaining a single error:

error: Failed dependencies:
	data(clamav) is needed by clamtk-6.00-1.el7.noarch

I have last version of Clamav installed, including Data:
	clamav	        Anti-virus software	                Running latest 0.101.1-6067.el7.art
  	clamav-db	Virus database for clamav	Running latest 0.101.1-6067.el7.art

If I try to install "clamav-data" (as required by the installation error message), via YUM, I got this error:
"Package clamav-data-0.101.1-1.el7.noarch is obsoleted by clamav-db-0.101.1-6067.el7.art.x86_64 which is already installed
Nothing to do"

So, clamav-data is obsolete, and the new one (clamav-db) is the one installed by YUM automatically with  "yum install clamav"

Is clamtk incompatible with the new clamav-db ?

Thanks

**Comment by dave-theunsub** [comment]
Hi,

Sorry for the installation issues. I'm unfamiliar with the .art files - is that a particular repo?  Are you using that in place of the EPEL repo?

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-95a6047bc6

If so, it might require a different build.

respectfully,
Dave M

**Comment by cham2019** [comment]
Thanks for the reply, I guess I solved it, considering this was about repo versions as you suggested.

I managed to disable this repository while installing clamav :  atomic ( atomicorp.com is a known library actually, but for the effect of using clamatk I had to disable it and using only YUM epel/x86_64)
Then, the installation was successful, but after enabling back atomic, this repo recognize the epel repo as obsolete:
[root@~]# yum --enablerepo=atomic update
Loaded plugins: fastestmirror, langpacks, priorities
Loading mirror speeds from cached hostfile
 * atomic: www6.atomicorp.com
 * epel: -------------------
 * webtatic: ----------------
atomic                                                                                        | 3.4 kB  00:00:00
240 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package clamav.x86_64 0:0.101.1-1.el7 will be updated
---> Package clamav.x86_64 0:0.101.1-6067.el7.art will be obsoleting
---> Package clamav-data.noarch 0:0.101.1-1.el7 will be obsoleted
---> Package clamav-db.x86_64 0:0.101.1-6067.el7.art will be obsoleting
---> Package clamav-filesystem.noarch 0:0.101.1-1.el7 will be obsoleted
---> Package clamav-lib.x86_64 0:0.101.1-1.el7 will be obsoleted
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================
 Package                   Arch                   Version                               Repository              Size
=====================================================================================================================
Installing:
 clamav                    x86_64                 0.101.1-6067.el7.art                  atomic                 1.0 M
     replacing  clamav-filesystem.noarch 0.101.1-1.el7
     replacing  clamav-lib.x86_64 0.101.1-1.el7
 clamav-db                 x86_64                 0.101.1-6067.el7.art                  atomic                  15 k
     replacing  clamav-data.noarch 0.101.1-1.el7
     replacing  clamav-filesystem.noarch 0.101.1-1.el7

Transaction Summary
=====================================================================================================================
Install  2 Packages

Total download size: 1.1 M
Is this ok [y/d/N]: n

;;;;;;;;;;;;;;;;;;;;;;;

I typed N, so I can continue to have the version compatible with clamtk and be able to install it.  

Atomic repo claims to be the most updated version of clamav:
0.101.1-6067  vs  0.101.1-1, and I guess they use a different "clamav-data" version called "clamav-db"

I have used atomic repos since some years ago, and it has worked well for me.  But since I wanted to try clamtk, I did what I explained above and worked.

Thanks

**Comment by dave-theunsub** [comment]
Cool, thanks for explaining. btw, if there are a decent number of people using that repo, I'm not against making another rpm for it. EPEL's been pretty consistent lately, so I just kept building for that.

respectfully,
Dave M
