### ISSUE TITLE
Lockup when downloading virus definitions

### ISSUE THREAD

**Issue by ampmaker** [dave-theunsub/clamtk#111]
I am running version 5.27 on a 32 bit computer and version 6.00 on a 64 bit computer. Both versions lockup trying to update the virus signatures. Last update was to signatures 25379.

**Comment by dave-theunsub** [comment]
Hi,

Please open a terminal window and type clamtk and press enter. Then, when the GUI comes up, try to update your signatures.  If there are any error messages in the terminal window, please post them here.

**Comment by ampmaker** [comment]
There are no error messages on either the 5.27 version or the 6.00 version. Once the computer locks up, the only way out of it is to shut down the computer and re-boot. The virus definitions have worked just fine through Monday, March 4th. This problem showed up on March 5th and has not worked since.

**Comment by dave-theunsub** [comment]
Ok, I've been trying to duplicate but haven't been able to yet. I just updated the sigs again and it went fine. I think this is a temporary issue with the mirrors.

Let's wait a day or two and see if the problem resolves itself.

**Comment by ampmaker** [comment]
Partial fix. On both computers I removed Clamtk entirely, then downloaded a fresh version 5.27 and installed version 5.27 to both computers. Now when I do the virus signature update it completes the process BUT nothing gets updated. The signature level stays at 25379 the "signatures are outdated" warning goes away. The only real change now is the computer does not get locked up.

When I close out Clamtk and restart it, the "signatures are outdated" warning reappears. Trying to update the signatures only repeats the above process. The update completes, the warning goes away and the signature level stays at 25379.

**Comment by ampmaker** [comment]
oops, closed issue by mistake

**Comment by ampmaker** [comment]
That partial fix was very temporary. When I turned off the computers and rebooted. Th original problem came back and now they both lockup when trying to update the virus signature level.

My first computer is a HP desktop running Ubuntu 16.04 32 bit. My second computer is a HP laptop running Ubuntu 18.04 64 bit. Both computers are connected by a LAN hardwire to my Comcast internet, telephone and wi-fi modem.

**Comment by keiththepoker** [comment]
Hi dave-theunsub
Great program – thanks a lot for your effort.

I'm having pretty much the same problems as ampmaker, but:

I run clamtk in terminal and get:

$ clamtk                                                                         
Gtk-Message **: Failed to load module "atk-bridge" at /usr/lib/x86_64-linux-gnu/perl5/5.24/Gtk2.pm line 126. 
LibClamAV Warning: **************************************************                      
LibClamAV Warning: ***  The virus database is older than 7 days!  ***                      
LibClamAV Warning: ***   Please update it as soon as possible.    ***                      
LibClamAV Warning: **************************************************

I then check for /usr/lib/x86_64-linux-gnu/
perl5/5.24/Gtk2.pm in dolphin, and it does not exist.

/usr/lib/x86_64-linux-gnu/ is there.

Devuan ascii OS on 100g partition, on HP8300USDT, 16G ram. 

Hope this helps.

**Comment by dave-theunsub** [comment]
Hi @keiththepoker ,

It's locking up for you? Also, what version of clamtk are you using?

respectfully
Dave M

**Comment by ampmaker** [comment]
It appears to be working OK for now. On Monday, the March 11th, I changed my updating of the signatures from manual to automatic updates and that finally allowed the latest signatures to be downloaded with no issues. Since that time my 64 bit computer has updated every day fine using automatic updates. My 32 bit computer update on Tuesday with automatic updates and today required switching to manual updates to work the automatic case did not work.
