### ISSUE TITLE
Clamtk 6 Debian 8 Jessie. Repos don't have libgtk3-perl--required for 6.00.

### ISSUE THREAD

**Issue by rbrband** [dave-theunsub/clamtk#113]
Error message indicates that dependency for libgtk3-perl can't be fulfilled. Result is a broken package and the need to uninstall clamtk. Synaptic Package Manager indeed indicates that libgtk3-perl doesn't exist--libgtk2-perl does. Re-installed Clamtk 5.27. Clamtk 5.27 indicates that "An update is available." Signatures are up to date: So, Clamtk 6 is  the update desired. No biggie....
Thanks!

**Comment by dave-theunsub** [comment]
Hi,

Thanks for the feedback. That version of the graphics library might only be available to Debian 9 ("stretch"). Unfortunately I don't have anything to do with Debian or Ubuntu repositories.

It'll be available if/when you upgrade, no doubt. In the meanwhile, I'm not against releasing new 5.xx versions when necessary.

Sorry I can't be of more help. Maybe some Debian folks can help further?

respectfully
Dave M

**Comment by rbrband** [comment]
Thanks, Dave! Debian is way too stodgy and conservative--nothing new.
Thanks for your great efforts here!

**Comment by dave-theunsub** [comment]
@rbrband ,

Cool! If we can help, just open another ticket. I'll close this one for now.

respectfully
Dave M
