### ISSUE TITLE
running sudo freshclam appears to not complete

### ISSUE THREAD

**Issue by rsramkis** [dave-theunsub/clamtk#114]
Hi,

I've been trying to get the CLAMTK application to update the virus definitions via the "sudo freshclam" command in terminal. I see the definition files getting downloaded but it does not complete. It will just appear to hang. Its been over a month and this continues to happen. 

The install is Clamtk 5.27-1 from the Manjaro standard repository.
Manjaro is running the 4.19.30-1 Kernel.

What can I do to address the issue? Thanks.

**Output from Terminal**
[rsruser@hanna ~]$ sudo freshclam -v
Current working dir is /var/lib/clamav
ClamAV update process started at Sat Mar 23 13:36:52 2019
Using IPv6 aware code
Max retries == 3
Querying current.cvd.clamav.net
TTL: 6
Software version from DNS: 0.101.1
main.cvd version from DNS: 58
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd version from DNS: 25397
Retrieving http://database.clamav.net/daily-25367.cdiff
Trying to download http://database.clamav.net/daily-25367.cdiff (IP: 104.16.219.84)
Downloading daily-25367.cdiff [100%]
cdiff_apply: Parsed 950 lines and executed 950 commands
Retrieving http://database.clamav.net/daily-25368.cdiff
Trying to download http://database.clamav.net/daily-25368.cdiff (IP: 104.16.219.84)
Downloading daily-25368.cdiff [100%]
cdiff_apply: Parsed 712 lines and executed 712 commands
Retrieving http://database.clamav.net/daily-25369.cdiff
Trying to download http://database.clamav.net/daily-25369.cdiff (IP: 104.16.219.84)
Downloading daily-25369.cdiff [100%]
cdiff_apply: Parsed 1852 lines and executed 1852 commands
Retrieving http://database.clamav.net/daily-25370.cdiff
Trying to download http://database.clamav.net/daily-25370.cdiff (IP: 104.16.219.84)
Downloading daily-25370.cdiff [100%]
cdiff_apply: Parsed 662 lines and executed 662 commands
Retrieving http://database.clamav.net/daily-25371.cdiff
Trying to download http://database.clamav.net/daily-25371.cdiff (IP: 104.16.219.84)
Downloading daily-25371.cdiff [100%]
cdiff_apply: Parsed 765 lines and executed 765 commands
Retrieving http://database.clamav.net/daily-25372.cdiff
Trying to download http://database.clamav.net/daily-25372.cdiff (IP: 104.16.219.84)
Downloading daily-25372.cdiff [100%]
cdiff_apply: Parsed 1035 lines and executed 1035 commands
Retrieving http://database.clamav.net/daily-25373.cdiff
Trying to download http://database.clamav.net/daily-25373.cdiff (IP: 104.16.219.84)
Downloading daily-25373.cdiff [100%]
cdiff_apply: Parsed 933 lines and executed 933 commands
Retrieving http://database.clamav.net/daily-25374.cdiff
Trying to download http://database.clamav.net/daily-25374.cdiff (IP: 104.16.219.84)
Downloading daily-25374.cdiff [100%]
cdiff_apply: Parsed 2747 lines and executed 2747 commands
Retrieving http://database.clamav.net/daily-25375.cdiff
Trying to download http://database.clamav.net/daily-25375.cdiff (IP: 104.16.219.84)
Downloading daily-25375.cdiff [100%]
cdiff_apply: Parsed 2140 lines and executed 2140 commands
Retrieving http://database.clamav.net/daily-25376.cdiff
Trying to download http://database.clamav.net/daily-25376.cdiff (IP: 104.16.219.84)
Downloading daily-25376.cdiff [100%]
cdiff_apply: Parsed 551 lines and executed 551 commands
Retrieving http://database.clamav.net/daily-25377.cdiff
Trying to download http://database.clamav.net/daily-25377.cdiff (IP: 104.16.219.84)
Downloading daily-25377.cdiff [100%]
cdiff_apply: Parsed 1060 lines and executed 1060 commands
Retrieving http://database.clamav.net/daily-25378.cdiff
Trying to download http://database.clamav.net/daily-25378.cdiff (IP: 104.16.219.84)
Downloading daily-25378.cdiff [100%]
cdiff_apply: Parsed 1324 lines and executed 1324 commands
Retrieving http://database.clamav.net/daily-25379.cdiff
Trying to download http://database.clamav.net/daily-25379.cdiff (IP: 104.16.219.84)
Downloading daily-25379.cdiff [100%]
cdiff_apply: Parsed 1225 lines and executed 1225 commands
Retrieving http://database.clamav.net/daily-25380.cdiff
Trying to download http://database.clamav.net/daily-25380.cdiff (IP: 104.16.219.84)
Downloading daily-25380.cdiff [100%]

**Comment by dave-theunsub** [comment]
Hi @rsramkis ,

Thanks for reporting this.

First, you don't need to use ```sudo freshclam``` - you can update from within clmatk itself.

Please paste back the output of ```cat ~/.clamtk/prefs```. I have a feeling you're running clamtk as a regular user, but updating the signatures as root. In which case, the fix will be to open Update Assistant, and change from one option to the other.

respectfully,  
Dave M

**Comment by rsramkis** [comment]
Hi Dave,

Thanks for the feedback. I have gone into Clamtk previously and setup the tool to auto update. Today I went in and switched it to manual update and then kicked off the update. The version of the virus definition files were 25377. I kicked off the manual update but it appeared to hang. I tried again and it appeared to complete. So not sure if it really updated.

**Output from prefs**
cat ~/.clamtk/prefs
Update=single
Whitelist=
ScanHidden=0
GUICheck=1
TruncateLog=1
SizeLimit=0
Recursive=1
Thorough=1
DupeDB=1
LastInfection=26 Sep 2018
HTTPProxy=0
Mounted=0

**Comment by dave-theunsub** [comment]
It's possible you don't have permissions to your own directory now because of sudo (maybe, anyway). Just for kicks, what is the result of  
```ls -ld ~/.clamtk```  
and  
```ls -l ~/.clamtk``` ?  

Also, if you were to switch to auto updating, this might be where the signatures you updated are now. You might try doing that - see if there is a difference between virus definition versions.  

respectfully,
Dave M

**Comment by rsramkis** [comment]
Hi Dave,

Thanks for the feedback. To make sure we are on the same page in regards to permissions I've summarized my tests and observations:

(1) Lets ignore the "sudo freshclam" as I am not using this command anymore.

(2) From my HOME directory I deleted the ".clamtk" folder with my regular user account. So if there was a permission issue then it should not let me delete it.

(3) After I deleted the folder I re-ran the update manually from Clamtk interface and the application recreated the ".clamtk" structure.

(4) I noticed the version of the virus definition changed from 25377 to 25380 when I manually ran the update. But the update ends up hanging. And then Manjaro asks me if I want to force quit the Clamtk tool. 

Here are the results you asked for:

rsruser@mani ~]$ ls -ld ~/.clamtk
drwxr-xr-x 6 rsruser rsruser 4096 Mar 25 21:29 /home/rsruser/.clamtk

[rsruser@mani ~]$ ls -l ~/.clamtk
total 20
drwxr-xr-x 3 rsruser rsruser 4096 Mar 25 21:30 db
drwxr-xr-x 2 rsruser rsruser 4096 Mar 25 21:29 history
-rw-r--r-- 1 rsruser rsruser  149 Mar 25 21:29 prefs
-rw-r--r-- 1 rsruser rsruser    0 Mar 25 21:29 restore
drwxr-xr-x 2 rsruser rsruser 4096 Mar 25 21:29 submit
drwxr-xr-x 2 rsruser rsruser 4096 Mar 25 21:29 viruses

I also captured the directory which I see the downloading of the dfinitions

[rsruser@mani db]$ ls -al
total 281348
drwxr-xr-x 3 rsruser rsruser      4096 Mar 25 21:30 .
drwxr-xr-x 6 rsruser rsruser      4096 Mar 25 21:29 ..
-rw-r--r-- 1 rsruser rsruser   1013248 Mar 25 21:29 bytecode.cld
drwxr-xr-x 3 rsruser rsruser      4096 Mar 25 21:30 clamav-060257ff6a845b33d41099e92abb50a7.tmp
-rw-r--r-- 1 rsruser rsruser 169158656 Mar 25 21:29 daily.cld
-rw-r----- 1 rsruser rsruser       290 Mar 25 21:30 freshclam.log
-rw-r--r-- 1 rsruser rsruser 117892267 Mar 25 21:29 main.cvd
-rw------- 1 rsruser rsruser        64 Mar 25 21:30 mirrors.dat

This was in the freshclam.log file:
--------------------------------------
ClamAV update process started at Mon Mar 25 21:30:04 2019
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Downloading daily-25378.cdiff [100%]
Downloading daily-25379.cdiff [100%]
Downloading daily-25380.cdiff [100%]

**Comment by dave-theunsub** [comment]
Hi @rsramkis ,

Ok, I'm back! Sorry about that.

Anyway, can you open a terminal window, type "clamtk" (obviously no quotes), enter, and try updating from there? Hopefully if there are any errors, they will show up in the terminal window. Then, please post them back here.

respectfully,  
Dave M

**Comment by rsramkis** [comment]
Hi Dave,

Do you want me to delete the ".clamtk" folder in the HOME directory before I kick off this command?

**Comment by dave-theunsub** [comment]
I would try it with the folder first. Then, if it doesn't work, back it up:
```mv ~/.clamtk ~/clamtkbackup```  
or something, and you can try from scratch.

respectfully,  
Dave M

**Comment by rsramkis** [comment]
(1) Test on latop called Mani
-Started with the directory being in place and the utility set at manual update. 
-The current virus definition version shows 25402. 
-Choose OK to let it update. 
-Front end reported 'Complete' and the antivirus definition changed to 25404. 
- No error in terminal or any text.

Will put up another post for the other laptop.

**Comment by rsramkis** [comment]
This is from "Hanna" laptop:

(1) **cat ~/.clamtk/prefs**

Thorough=0
DupeDB=1
Update=shared
ScanHidden=0
SizeLimit=0
Whitelist=
Recursive=0
Mounted=0
LastInfection=Never
TruncateLog=1
GUICheck=1
HTTPProxy=0


(2) Check Permissions

**ls -ld ~/.clamtk**
----------------
drwxr-xr-x 6 rsruser rsruser 4096 Mar 28 23:27 /home/rsruser/.clamtk


**ls -l ~/.clamtk** 
----------------
total 20
drwxr-xr-x 2 rsruser rsruser 4096 Mar 28 23:27 db
drwxr-xr-x 2 rsruser rsruser 4096 Mar 28 23:27 history
-rw-r--r-- 1 rsruser rsruser  149 Mar 28 23:27 prefs
-rw-r--r-- 1 rsruser rsruser    0 Mar 28 23:27 restore
drwxr-xr-x 2 rsruser rsruser 4096 Mar 28 23:27 submit
drwxr-xr-x 2 rsruser rsruser 4096 Mar 28 23:27 viruses

**(3) Run clamtk from terminal (no sudo)**
-start with antivirus definition 25366
-set update to manual
-Choose update button and it said "Downloading".
-You can see the Antivirus definition change to 25380.
-The update software appears to freeze. Prompted to force quit.
-Checked system monitor and can see the 'freshclam' process varying between 23 and 24 percent. 30 mins pass and it never shuts down.
-Had to force shut down the process to close clamtk front end.
-Freshclam does not shutdown. Stays in memory with 23-24 percent cpu. Ended this process by killing it.

**Terminal logs:**

[rsruser@hanna ~]$ clamtk
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine", at /usr/lib/perl5/5.28/vendor_perl/Gtk2.pm line 126.
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
Killed
[rsruser@hanna ~]$

**Comment by dave-theunsub** [comment]
Hi @rsramkis ,

No differences between the configuration of the systems that you can think of?

How about ```sudo freshclam -v``` on the problem system (hanna)? Maybe the verbose option can give us more information.


respectfully, 
Dave M

**Comment by rsramkis** [comment]
Hi Dave,

**Both systems:**
-run the same version of Manjaro
-Have user accounts with the same permissions.
-Both systems used to run "sudo freshclam" and always complete.
-Both systems using X11 with Gnome

**Difference:**
-Hanna is 1 year older install and has an Nvidia Video card.
-When running sudo freshclam failed on:

Laptop Mani - would download 3 or 4 file definitions and hang.
Laptop Hanna - would download 14 file definitions and hang.

The first post for this issue is Hanna terminal output.

**sudo freshclam output for Laptop Hanna:**

[rsruser@hanna ~]$ sudo freshclam -v
[sudo] password for root: 
Current working dir is /var/lib/clamav
ClamAV update process started at Sun Mar 31 08:46:56 2019
Using IPv6 aware code
Max retries == 3
Querying current.cvd.clamav.net
TTL: 1066
Software version from DNS: 0.101.2
WARNING: Your ClamAV installation is OUTDATED!
WARNING: Local version: 0.101.1 Recommended version: 0.101.2
DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
main.cvd version from DNS: 58
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd version from DNS: 25405
Retrieving http://database.clamav.net/daily-25367.cdiff
Trying to download http://database.clamav.net/daily-25367.cdiff (IP: 104.16.219.84)
Downloading daily-25367.cdiff [100%]
cdiff_apply: Parsed 950 lines and executed 950 commands
Retrieving http://database.clamav.net/daily-25368.cdiff
Trying to download http://database.clamav.net/daily-25368.cdiff (IP: 104.16.219.84)
Downloading daily-25368.cdiff [100%]
cdiff_apply: Parsed 712 lines and executed 712 commands
Retrieving http://database.clamav.net/daily-25369.cdiff
Trying to download http://database.clamav.net/daily-25369.cdiff (IP: 104.16.219.84)
Downloading daily-25369.cdiff [100%]
cdiff_apply: Parsed 1852 lines and executed 1852 commands
Retrieving http://database.clamav.net/daily-25370.cdiff
Trying to download http://database.clamav.net/daily-25370.cdiff (IP: 104.16.219.84)
Downloading daily-25370.cdiff [100%]
cdiff_apply: Parsed 662 lines and executed 662 commands
Retrieving http://database.clamav.net/daily-25371.cdiff
Trying to download http://database.clamav.net/daily-25371.cdiff (IP: 104.16.219.84)
Downloading daily-25371.cdiff [100%]
cdiff_apply: Parsed 765 lines and executed 765 commands
Retrieving http://database.clamav.net/daily-25372.cdiff
Trying to download http://database.clamav.net/daily-25372.cdiff (IP: 104.16.219.84)
Downloading daily-25372.cdiff [100%]
cdiff_apply: Parsed 1035 lines and executed 1035 commands
Retrieving http://database.clamav.net/daily-25373.cdiff
Trying to download http://database.clamav.net/daily-25373.cdiff (IP: 104.16.219.84)
Downloading daily-25373.cdiff [100%]
cdiff_apply: Parsed 933 lines and executed 933 commands
Retrieving http://database.clamav.net/daily-25374.cdiff
Trying to download http://database.clamav.net/daily-25374.cdiff (IP: 104.16.219.84)
Downloading daily-25374.cdiff [100%]
cdiff_apply: Parsed 2747 lines and executed 2747 commands
Retrieving http://database.clamav.net/daily-25375.cdiff
Trying to download http://database.clamav.net/daily-25375.cdiff (IP: 104.16.219.84)
Downloading daily-25375.cdiff [100%]
cdiff_apply: Parsed 2140 lines and executed 2140 commands
Retrieving http://database.clamav.net/daily-25376.cdiff
Trying to download http://database.clamav.net/daily-25376.cdiff (IP: 104.16.219.84)
Downloading daily-25376.cdiff [100%]
cdiff_apply: Parsed 551 lines and executed 551 commands
Retrieving http://database.clamav.net/daily-25377.cdiff
Trying to download http://database.clamav.net/daily-25377.cdiff (IP: 104.16.219.84)
Downloading daily-25377.cdiff [100%]
cdiff_apply: Parsed 1060 lines and executed 1060 commands
Retrieving http://database.clamav.net/daily-25378.cdiff
Trying to download http://database.clamav.net/daily-25378.cdiff (IP: 104.16.219.84)
Downloading daily-25378.cdiff [100%]
cdiff_apply: Parsed 1324 lines and executed 1324 commands
Retrieving http://database.clamav.net/daily-25379.cdiff
Trying to download http://database.clamav.net/daily-25379.cdiff (IP: 104.16.219.84)
Downloading daily-25379.cdiff [100%]
cdiff_apply: Parsed 1225 lines and executed 1225 commands
Retrieving http://database.clamav.net/daily-25380.cdiff
Trying to download http://database.clamav.net/daily-25380.cdiff (IP: 104.16.219.84)
Downloading daily-25380.cdiff [100%]

**Comment by dave-theunsub** [comment]
Hi @rsramkis ,

Well, I'm a bit stumped here. @SunyataZero and I think this may be more of an issue with freshclam or networking. We could be wrong, but I'm not sure what would explain this from a clamtk perspective.

I'm happy to keep digging, but without more information it'll be slow going. Sorry for not being able to help much here.

respectfully,
Dave M

**Comment by rsramkis** [comment]
Any update on this issue? @dave-theunsub @SunyataZero

**Comment by dave-theunsub** [comment]
We've also received an email from an Ubuntu Mint user on this same topic. The problem is that I cannot duplicate it. I've tried multiple distros, switched back and forth between manual and automated updates, and cannot duplicate it yet.

Here's another attempt if you're up for it. Run:
`strace -o clamtk.debug clamtk`

from the command line. If you don't have strace installed, you may have to grab that first. The amount of output can be overwhelming, but it's very verbose and could help. Please post the "clamtk.debug" file - or better yet, email it to me in case there's sensitive directory/filename/etc information so it won't get posted publicly.

respectfully,
Dave M

**Comment by rsramkis** [comment]
Hi Dave. I can create the debug trace for you. Where can I e-mail it too?

**Comment by dave-theunsub** [comment]
dave.nerd@gmail should work (adding the .com, of course :)

Like I said, I've tried Ubuntu, Debian, Fedora, and CentOS and cannot duplicate yet... hopefully this will be helpful.  Thanks!!

**Comment by rsramkis** [comment]
Hi Dave,

I noticed the update functionality is now working in the front end tool (Clamtk) when using Manjaro with the latest update. Additional below is the command line running the update. If the output is up to par perhaps we should close this defect?

**Update from Command line**
sudo freshclam -v
[sudo] password for root: 
Current working dir is /var/lib/clamav
ClamAV update process started at Sun Jul 28 14:08:10 2019
Using IPv6 aware code
Max retries == 3
Querying current.cvd.clamav.net
TTL: 465
Software version from DNS: 0.101.2
main.cvd version from DNS: 58
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd version from DNS: 25524
Retrieving http://database.clamav.net/daily-25367.cdiff
nonblock_connect: connect(): fd=4 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:db54)
Trying to download http://database.clamav.net/daily-25367.cdiff (IP: 104.16.219.84)
Downloading daily-25367.cdiff [100%]
cdiff_apply: Parsed 950 lines and executed 950 commands
Retrieving http://database.clamav.net/daily-25368.cdiff
Trying to download http://database.clamav.net/daily-25368.cdiff (IP: 104.16.219.84)
WARNING: getfile: daily-25368.cdiff not found on database.clamav.net (IP: 104.16.219.84)
WARNING: getpatch: Can't download daily-25368.cdiff from database.clamav.net
Querying daily.25368.102.0.0.6810DB54.ping.clamav.net
Can't query daily.25368.102.0.0.6810DB54.ping.clamav.net
Retrieving http://database.clamav.net/daily-25368.cdiff
Trying to download http://database.clamav.net/daily-25368.cdiff (IP: 104.16.218.84)
WARNING: getfile: daily-25368.cdiff not found on database.clamav.net (IP: 104.16.218.84)
WARNING: getpatch: Can't download daily-25368.cdiff from database.clamav.net
Querying daily.25368.102.0.0.6810DA54.ping.clamav.net
Can't query daily.25368.102.0.0.6810DA54.ping.clamav.net
Retrieving http://database.clamav.net/daily-25368.cdiff
Trying to download http://database.clamav.net/daily-25368.cdiff (IP: 104.16.219.84)
WARNING: getfile: daily-25368.cdiff not found on database.clamav.net (IP: 104.16.219.84)
WARNING: getpatch: Can't download daily-25368.cdiff from database.clamav.net
Querying daily.25368.102.0.0.6810DB54.ping.clamav.net
Can't query daily.25368.102.0.0.6810DB54.ping.clamav.net
WARNING: Incremental update failed, trying to download daily.cvd
Whitelisting short-term blacklisted mirrors
Retrieving http://database.clamav.net/daily.cvd
nonblock_connect: connect(): fd=4 errno=101: Network is unreachable
Can't connect to port 80 of host database.clamav.net (IP: 2606:4700::6810:da54)
Trying to download http://database.clamav.net/daily.cvd (IP: 104.16.219.84)
Downloading daily.cvd [100%]
Loading signatures from daily.cvd
Properly loaded 1685755 signatures from new daily.cvd
daily.cvd updated (version: 25524, sigs: 1685755, f-level: 63, builder: raynman)
Querying daily.25524.102.1.0.6810DB54.ping.clamav.net
Can't query daily.25524.102.1.0.6810DB54.ping.clamav.net
bytecode.cvd version from DNS: 330
Retrieving http://database.clamav.net/bytecode-329.cdiff
Trying to download http://database.clamav.net/bytecode-329.cdiff (IP: 104.16.219.84)
Downloading bytecode-329.cdiff [100%]
cdiff_apply: Parsed 905 lines and executed 902 commands
Retrieving http://database.clamav.net/bytecode-330.cdiff
Trying to download http://database.clamav.net/bytecode-330.cdiff (IP: 104.16.219.84)
Downloading bytecode-330.cdiff [100%]
cdiff_apply: Parsed 4 lines and executed 4 commands
Loading signatures from bytecode.cld
Properly loaded 94 signatures from new bytecode.cld
bytecode.cld updated (version: 330, sigs: 94, f-level: 63, builder: neo)
Querying bytecode.330.102.1.0.6810DB54.ping.clamav.net
Can't query bytecode.330.102.1.0.6810DB54.ping.clamav.net
Database updated (6252098 signatures) from database.clamav.net (IP: 104.16.219.84)
WARNING: Clamd was NOT notified: Can't connect to clamd through /run/clamav/clamd.ctl: No such file or directory

**Comment by dave-theunsub** [comment]
Hi @rsramkis ,

If you can vouch for it working now, then sounds good - please close it. I can't verify either way, unfortunately. If the bug comes up again, it can always be re-opened.

respectfully, 
Dave M

**Comment by rsramkis** [comment]
I'm going to close the issue (unknown what fixed the issue between the build deliveries from the Arch repositories.
