### ISSUE TITLE
directory is whitelisted but still receiving mail from clamav about infected files

### ISSUE THREAD

**Issue by anschwa** [dave-theunsub/clamtk#115]
Hello, I have a directory whitelisted that contains an "infected" file used in a project for testing purposes. However, I receive mail from clamav about this file during scheduled scans using clamtk. 

Is there a way to prevent this mail message about the dummy file?
I am using clamtk 6.0.0 on debian stable.

Thanks.

**Comment by dave-theunsub** [comment]
Hi @anschwa ,

I was planning to re-add the whitelist portion to the scheduler. I think I can do it for 6.01. Note that assuming I do, you will have to delete your current scheduled scan and re-add it.

respectfully,  
Dave M

**Comment by anschwa** [comment]
Very cool, thanks!
