### ISSUE TITLE
When I run clamtk in Linus Cinnamon Mint 18.3 History shows 20 items items found but not in quarantine 

### ISSUE THREAD

**Issue by jflake10** [dave-theunsub/clamtk#116]
I like the program. I have been running it for 5 days and the only issue is that HISTORY shows the pup files, but nothing shows in quarantine. Is there a suggested

**Comment by dave-theunsub** [comment]
Hi @jflake10 ,

Apologies for the late response.. completely missed the notification in my inbox.

Anyway, there is no automatic quarantine or delete anymore... that can be pretty dangerous when PUAs are involved. I recommend removing the checkbox from the PUA scanning item in Settings.

See here for more on PUAs.

https://wikipedia.org/wiki/Potentially_unwanted_program

respectfully,   
Dave M

**Comment by dave-theunsub** [comment]
Closing for now. Re-open or open a new issue for further questions.
