### ISSUE TITLE
Wide character at /usr/share/perl5/ClamTk/Scan.pm

### ISSUE THREAD

**Issue by Ro-Den** [dave-theunsub/clamtk#118]
It was mentioned in https://github.com/dave-theunsub/clamtk/issues/99 but wasn't fixed.

One can fix it here:

https://github.com/dave-theunsub/clamtk/blob/996ca5590b5be838a0616c17bda9461d0ca297ac/lib/Scan.pm#L559

with `= split / /, strftime( '%m %d %Y', localtime );`

and/or here:

https://github.com/dave-theunsub/clamtk/blob/996ca5590b5be838a0616c17bda9461d0ca297ac/lib/Scan.pm#L573

with `= $paths . "/" . "$day-$mon-$year" . '.log';`

P.S: It's "$day-$mon-$year", bloody Yankees. Very truly yours, the rest of the world.

**Comment by dave-theunsub** [comment]
I'll put a fix in for this in version 6.05. 6.04 will be pushed soon and I'd just as soon not add another option in this upcoming version.

Right now, maybe I can add an option for day-mon-year and mon-day-year. Personally I like year-mon-day; easier for sorting too.

Thanks,
Dave M

**Comment by dave-theunsub** [comment]
The "wide character" issue is fixed in 6.09. I'll tackle the date thing in another release. Thanks!
