### ISSUE TITLE
ClamTK Analysis Button

### ISSUE THREAD

**Issue by eqjjh** [dave-theunsub/clamtk#122]
Is not described in the program (by hovering over) or in the Documentation (http://clamtk.sourceforge.net/help/results-clamtk.html) what the "Analysis" button does. Screenshot in the above link is outdated and does not show the button.

I first thought I would get some more information on why a file was identified but nothing happened.

**Comment by dave-theunsub** [comment]
Hi @eqjjh ,

The Analysis button shows you what Virustotal (https://virustotal.com) knows about a file you select. If it doesn't know anything, you can submit it to be scanned by a variety of virus scanners.

I agree that there should be more information, though. I'll come up with something more for that.

Thanks,
Dave M

**Comment by dave-theunsub** [comment]
Also, I just added a Help button which explains this. It will be in 6.05. I should've added it a long time ago, but your reminder is the kick I needed. :)

Thanks,  
Dave M

**Comment by dave-theunsub** [comment]
Fixed in 6.06. Please open a new ticket if necessary.

Thanks,  
Dave M
