### ISSUE TITLE
Interface complementary details

### ISSUE THREAD

**Issue by Ricky-Tigg** [dave-theunsub/clamtk#129]
**OS:** Fedora 34, **clamtk**: v.6.11; **clamav**: v.0.103.3 64 bit

![clamtk_6 11-1_GUI](https://user-images.githubusercontent.com/26058215/123807289-66049f00-d8f8-11eb-83e2-f18941c1bf2f.png)

GUI is well designed and appropriately minimalist.  It may lack those relevant details:

- The product is named with a generic expression – _Virus Scanner_ – which makes its identification inadequate. Naming it with its full qualification – e.g. _ClamTk virus scanner_ –  would allow for such identification.
- At section _About_, the version of clamtk's underlying component clamav, with its bit version – e.g._clamav v.0.103.3 64 bit_ –, is worth a mention. Mentioning it will ensure that the application is running against the expected version of that component.
- At section _Update,_ the date the virus signatures file was updated is worth a mention as it is the only detail that explicitly indicates how old the signatures are.

**Comment by dave-theunsub** [comment]
Hi @Ricky-Tigg ,

Great suggestions!

* You're right; it's generic. It used to be fully spelled out, but apparently some languages do words in a different order (might not be explaining it right). So, the easier thing to do was just remove a word. Good idea, but I need to find the emails/bug reports and figure out how to do it for all languages.
* That's doable; it was in there before, too. The mistake I made was putting an icon indicating if it was an outdated version or not, and end users do not usually control this - package managers do. Got lots of panicky emails over that one. :|  This time, just the version.
* Can you spell out a little more what you mean by this one?  Where exactly do we put the date or age or ...

respectfully,
Dave M

**Comment by Ricky-Tigg** [comment]
Hello. The mention of the creation **time stamp** associated to the file containing the antivirus signatures could be integrated into that interface, into a third right-sided column – which could be named _Update_ – regards to the _Installed_-named column.

![clamtk_v 6 11_Update_section](https://user-images.githubusercontent.com/26058215/124270949-82494b80-db45-11eb-8871-ba6a1cb672eb.png)

New suggestion | While [Linux Malware Detect](https://www.rfxn.com/projects/linux-malware-detect/) is installed and configured – at /usr/local/maldetect/conf.maldet –  to be enabled – with the parameter scan_clamscan="1" – in order to act in ClamAV, then its allowance would be worth an option – e.g. _Enable Linux Malware Detect 's malware signatures in scans_ –  in that interface and could be located under _Check for updates to this program_.

![clamtk_v 6 11_Settings_section](https://user-images.githubusercontent.com/26058215/124270282-ace6d480-db44-11eb-8517-b5e4b5d0b5e2.png)

**Comment by dave-theunsub** [comment]
Hi @Ricky-Tigg ,

The only place I can see where we can put the ClamAV (engine) version is by appending it to the `set_comments` portion. See image. Unless you have any objections, I'll add it there for now.

For adding clamtk to the 'Virus Scanner' part - I'll add it to the things to be translated but we'll have to give them time to do it.

The new one will take time to see if it's possible.

respectfully,
![about_engine](https://user-images.githubusercontent.com/1854718/124431692-4d501b00-dd36-11eb-9d90-dc4e7617a283.png)

Dave M

**Comment by dave-theunsub** [comment]
Hi @Ricky-Tigg ,

Here is the Date column, added to the Update interface (showing a Spanish language view). It's not a timestamp; it's the date of the signatures.

![add_date_column](https://user-images.githubusercontent.com/1854718/124434263-470f6e00-dd39-11eb-9043-f483721f1045.png)


respectfully,
Dave M

**Comment by dave-theunsub** [comment]
Hi @Ricky-Tigg ,

Also, forget my earlier comment about needing to give translators time. The string "ClamTk Virus Scanner" was already in the language file, and only needed to be updated in one area, so that's done too.

respectfully,
Dave M

**Comment by Ricky-Tigg** [comment]
Didi you notice that text  "_ClamTk (...) "Artistic License"._" is not available for translation at [Launchpad](https://translations.launchpad.net/clamtk)?

![ClamTk_v 6 11_Credits-tab](https://user-images.githubusercontent.com/26058215/124464597-106b3f00-dd9d-11eb-9e37-172426aa9ddb.png)

**Comment by dave-theunsub** [comment]
Hi @Ricky-Tigg ,

Yes, not too concerned with that part right now.

I'm building v6.12 right now. Only the Fedora rpm is done; waiting for the Ubuntu to get done updating so I can get to debs.

respectfully,
Dave M
