### ISSUE TITLE
Issue running scan with clamav 0.104

### ISSUE THREAD

**Issue by billysmt** [dave-theunsub/clamtk#134]
**Describe the bug**
Downloaded and installed latest clamav (0.104) and clamtk (6.13) and attempting to run a directory scan, I get the following message with a "ClamTK" is not responding, Force Quit or Wait dialog.  Waiting just seems to sit there and do nothing, occasionally comes up with a scan complete 0 files processed dialog.
```
clamscan version = >103.2<
```
**To Reproduce**

**Expected behavior**
I'd expect the scan to run.

**Screenshots**
Ignore the first half.  I was attempting to install from apt and it was only installing 6.03, I swapped to downloading the debian and that started the clamscan version message on directory scan.
![image](https://user-images.githubusercontent.com/1816107/136042901-9cc052a4-d318-4c4d-91ea-6f28b4ea7b92.png)

**OS:**
 - Distribution: PopOS
 - Version: 21.04

**clamtk:**
 - Version: [6.13]

**Additional context**

**Comment by billysmt** [comment]
Huh, so in the time it took to create the ticket it finally started running.  Still seems odd that it took that long to start but maybe not an issue.  sorry for the possible false alarm.

**Comment by dave-theunsub** [comment]
Thanks for responding!
