### ISSUE TITLE
ClamTk 6.13 and 6.14 dosen't start anymore in Ubuntu- Mate 20.04 LTS

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [dave-theunsub/clamtk#136]
**Describe the bug**
ClamTK do not open with error massage in the Terminal : "Symbol �alarm� nicht im Thema Radiant-MATE vorhanden at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67."
I have updated to ClamTK 6.14 from git but dosen't help.

My System is Unbuntu- Mate 20.04.3 LTS with Kernel Linux 5.11.0-40-lowlatency x86_64 and MATE 1.24.0.
In the Flatpak version of ClamTK 6.13 the same error in my System.

Add any other context about the problem here. For example, has this problem always occurred, or is it new?
It is a new problem. I used ClamTk last time a few weeks ago and it do his job good at this time.

**Comment by dave-theunsub** [comment]
Hi @SaschaVasarrhelyi ,

Thank you for reporting.

I think it can't find the icons/images it needs.  Just for testing, can you try to switch themes and see if it works then?  There are probably some extra themes that come with the distro.
