### ISSUE TITLE
database for Linux viruses?

### ISSUE THREAD

**Issue by Golddouble** [dave-theunsub/clamtk#143]
Hello,

Has clamtk only a database for Windows viruses or has it also a database for (the few) Linux viruses?

Would appreciate some answer. Thank you.

**Comment by dave-theunsub** [comment]
Hi @Golddouble ,

The ClamAV signatures are for both Linux and Windows.

respectfully,  
Dave M

**Comment by Golddouble** [comment]
Thank you.
