### ISSUE TITLE
Unable to delete previous analysis result

### ISSUE THREAD

**Issue by sp1cyf0x** [dave-theunsub/clamtk#150]
**Describe the bug**
Unable to delete previous analysis result.

**To Reproduce**
1. Go to Analysis.
2. Click on Analysis.
3. Go to View or delete previous results.
4. Click on the select box. 
5. Choose an analysis result.
6. Click on the trash bin button.
7. See error: Nothing happen on the GUI, the chosen analysis result is not deleted.

**Expected behavior**
The chosen analysis result is deleted and can no longer be viewed.

**Screenshots**
![Screenshot_20221225_213655 cleaned](https://user-images.githubusercontent.com/24849056/209472191-eed65f4e-3823-4a96-9630-e08025c5ebf8.png)
Example: An attempt to delete the analysis result for the file `ENG.7z`.

**OS:**
 - Distribution: Arch Linux.
 - Version: Rolling release, all packages are up to date as of 25 Dec 2022.

**clamtk:**
 - Version: 6.14-1 on [the Community repository](https://archlinux.org/packages/community/any/clamtk).

**Additional context**
This problem has always occurred since the installation of ClamTK.
Console output:
```
*** unhandled exception in callback:
***   Can't locate object method "get_active_text" via package "Gtk3::ComboBox" at /usr/share/perl5/vendor_perl/ClamTk/Analysis.pm line 431.
***  ignoring at /usr/share/perl5/vendor_perl/Gtk3.pm line 1154.
```

**Comment by dave-theunsub** [comment]
Hi @sp1cyf0x ,

Can confirm. Looking to see what needs to be changed to fix this.  Might have to be changed to this:  https://docs.gtk.org/gtk3/method.ComboBoxText.get_active_text.html .

respectfully,
Dave M

**Comment by dave-theunsub** [comment]
Hi @sp1cyf0x ,

I believe it's fixed now and pushed.  I still have to build packages though.  If you can test it, please let me know how it works for you.

respectfully,
Dave M

**Comment by sp1cyf0x** [comment]
Hey @dave-theunsub. I tried building from source using Arch's PKGBUILD, but it outputted this on launch:
```
Can't locate Proc/ProcessTable.pm in @INC (you may need to install the Proc::ProcessTable module) (@INC contains: /usr/lib/perl5/5.36/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.36/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.36/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/ClamTk/Startup.pm line 16.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/ClamTk/Startup.pm line 16.
Compilation failed in require at /usr/bin/clamtk line 35.
BEGIN failed--compilation aborted at /usr/bin/clamtk line 35.
```
I also tried the method in the README file, that had the same result.
Maybe it is just me building it wrong. It would be great if you could help me build the package.

**Comment by dave-theunsub** [comment]
Hi @sp1cyf0x ,

No, I messed up.  I was working on different functionality and did not finish it - then forgot to remove it since it wasn't going to be in 6.15... :(

I re-pushed that file, so it should work now.  If not, let me know and I'll just upload a build here for you to try that should work.

respectfully,
Dave M

**Comment by sp1cyf0x** [comment]
Hey @dave-theunsub, I just built it again and was able to delete the analysis result. No errors spotted.

**Comment by dave-theunsub** [comment]
Hi @sp1cyf0x ,

Excellent, thanks for the feedback.  Hopefully I can get 6.15 out soon.

respectfully,
Dave M
