### ISSUE TITLE
Scan a whole computer

### ISSUE THREAD

**Issue by FRANEKbinbanek** [dave-theunsub/clamtk#151]
Hey!
I like using Clamtk for my Linux builds, but there is one thing that annoys me every time I am using clamtk. that thing is lack of option to scan the ENTIRE system from A to Z (including hidden files).
I hope this option will be avaible soon...

**Comment by dave-theunsub** [comment]
Hi @FRANEKbinbanek ,

You can do this.  You have to enable recursive scanning and the scan hidden files options in Settings, and then do a directory scan.  In the directory scan, you'll have to look for the "computer" option or navigate to the "/" directory.

Note that I don't really recommend this. I think you should use a rootkit scanner for things like that (e.g., rkhunter).

respectfully,
Dave M

**Comment by FRANEKbinbanek** [comment]
Ok thanks

**Comment by FRANEKbinbanek** [comment]
Ok thanks
