### ISSUE TITLE
Settings help 

### ISSUE THREAD

**Issue by Rik44444** [dave-theunsub/clamtk#153]
quick question: I am not an expert user, and am not sure what many of the Settings mean. Is there a support document explaining the various help options + (and this would be especially helpful) are there recommended settings for default users?

**Comment by dave-theunsub** [comment]
Hi @Rik44444 ,

I did write some information in the [README.md](https://github.com/dave-theunsub/clamtk/blob/master/README.md) that should be helpful.  I admit that it is not very extensive.

If there are any questions you have beyond that, please feel free to just ask!

respectfully,
Dave M

**Comment by dave-theunsub** [comment]
Closing for now.  Just open new issues for any specific problems or questions, and we'll be happy to help.

respectfully,  
Dave M
