### ISSUE TITLE
Virustotal privacy warning before upload or sending file hash only

### ISSUE THREAD

**Issue by richardpackham** [dave-theunsub/clamtk#155]
**Is your feature request related to a problem? Please describe.**
The analysis section does not make it clear that you are uploading a file to virustotal unless you happen to click on the "What is this" button. There is potential to upload sensitive information accidentally which can be downloaded by any virustotal customer.  

**Describe the solution you'd like**
1. Consider adding option to just submit the hash of the file rather than the file contents to preserve privacy
2. Before submitting a file add a step to confirm that the file does not contain sensitive information before upload (present the information from the "What is this" button
3. Add the link to virustotal file removal requests if sensitive information is uploaded

**Comment by dave-theunsub** [comment]
Hi @richardpackham ,

Thank you for the feedback.

1. For this one, it's already implemented.  You can test this yourself by going [here](https://www.eicar.org/download-anti-malware-testfile/), downloading (e.g.) eicar.com, and submitting this one in the analysis section.
2. The current message (assuming the file has not been previously submitted) is pretty spartan.  Maybe another quick popup to warn them, or just replacing the current one would be better.
3. There *is no* removal ability.  I've had to plead with them on more than one occasion to remove a sensitive file that had been uploaded (e.g., a tax return).  So, I don't know how to handle this one, but it does add importance to the 2nd point.

I'll work on the popup.

respectfully,
Dave M

**Comment by dave-theunsub** [comment]
Fixed in 6.16.  Thanks for reporting this.

respectfully,  
Dave M
