### ISSUE TITLE
windows install 

### ISSUE THREAD

**Issue by TwoDogs2** [dave-theunsub/clamtk#156]

**Comment by dave-theunsub** [comment]
Hi @TwoDogs2 ,

No, clamtk is only for Linux.  ClamAV itself, though, has a Windows download:  https://www.clamav.net/ .  I have not checked it out yet.

respectfully,  
Dave M

**Comment by dave-theunsub** [comment]
Closing - let me know if there are any other questions.

**Comment by TwoDogs2** [comment]
Thank you very much

**Comment by JL2210** [comment]
I think the old versions that actually use Tk could work - the only problem is that they hardcode the paths of the binaries for some old Fedora rpm
