### ISSUE TITLE
'scan files beginning with a dot' is not working, at least on linux mint 21.1 with the latest version from the LM store/repository

### ISSUE THREAD

**Issue by peppermintstarman** [dave-theunsub/clamtk#157]
**Describe the bug**
I have the option to scan files beginning with dot enabled in the clamTK GUI, but when I scan, using the clamTK GUI, I cannot see any of the files or folders that start with a dot.

**To Reproduce**
1. open the app
2. enable  'scan files beginning with dot '.'
3. click on the GUI option for scan a file (or scan a directory)
4. there are no files or folders visible that begin with a dot in the interface, so I cannot scan them.

**Expected behavior**
I should be able to see the files and folders that start with a dot '.'.

**OS:**
Linux Mint 21.1

**clamtk:**
 - Version: [6.07] (it is the latest one available in the app store/repository as of speaking, in linux mint).

**Additional context**
it did not occur some months ago, but it has been like this for a while now.

**Comment by dave-theunsub** [comment]
Hi @peppermintstarman ,

Are you able to try 6.16 to see if it works?  I'll look at it more this weekend as well.

Dave M

**Comment by peppermintstarman** [comment]
@dave-theunsub Yes, I have tried 6.16 in the same environment, although admittedly it was the flatpak fork of this project which is from the following: https://github.com/flathub/com.gitlab.davem.ClamTk (as it is on the linux mint repo). The same issue was present. It is a bit unfortunate that linux mint repo is running the older version for the deb version but it is what it is, I guess. I presume the flatpak version/fork which is up to date, and has the same issue, is for the same reason (though maybe not of course). I will consider testing the recent deb also and update it here if I do so.

**Comment by dave-theunsub** [comment]
Hi @peppermintstarman ,

Just to clarify - do you mean you cannot select a file or folder to scan, or that you can select them but clamtk won't scan them?

Dave M

**Comment by peppermintstarman** [comment]
Hi @dave-theunsub,

To clarify, the files that start with '.' (the so called 'hidden files') are not showing in any instance, so I can neither see them nor can I select them. The standard files and folders are showing, however, and I can see, select and scan them as expected. The option to scan files and folders beginning with '.' is enabled in the GUI, and there is no extra option in the GUI that I can find regarding showing those files.

In the ClamTK prefs document it is showing 'ScanHidden=1', for your information.

**Comment by dave-theunsub** [comment]
Hi @peppermintstarman ,

In the "select a directory" dialog - if you right-click in there, is the "show hidden files" option highlighted or showing it's on?  See attached image.

Dave M

![Screenshot from 2023-11-10 09-30-54](https://github.com/dave-theunsub/clamtk/assets/1854718/ddcebd63-0287-4438-8a2e-b1bce777174f)

**Comment by peppermintstarman** [comment]
Hi @dave-theunsub,

Thank you for looking into this and finding the solution. Seems like I overlooked trying this within the app, for some reason, but yes, it is indeed the way to see the dot files. Issue resolved.
