### ISSUE TITLE
I'm simply trying to ask about OR report an issue with ClamTK. After the latest update, it will not scan for issues! 

### ISSUE THREAD

**Issue by William1Neil** [dave-theunsub/clamtk#162]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS:**
 - Distribution: [e.g. Ubuntu, Fedora]
 - Version [e.g. 20.04]

**clamtk:**
 - Version: [6.08]

**Additional context**
Add any other context about the problem here. For example, has this problem always occurred, or is it new?

**Comment by dave-theunsub** [comment]
Hi @William1Neil ,

I'm sorry, I'm not sure what you are reporting.

Are you using version 6.08? Or the newest version?

If this is something happening when you are trying to scan, do this:

* Open a terminal window
* Type `clamtk`
* Now try to do what you want
* Check the terminal window to see if there are any error messages. If so, please post them here.

Any screenshots or anything else you can provide will be helpful.

respectfully,
Dave M

**Comment by William1Neil** [comment]
Thanks for responding Dave.
Today I did another update and everything works fine.
Perhaps I just didn't wait long enough for the program to begin the scan, but I felt that I waited for at least 3 minutes with nothing happening. 
Anyway, all is good.
May I also thank you and your team for making this program available to the Linux world.

**Comment by dave-theunsub** [comment]
Hi @William1Neil ,

Thank you for updating!  If everything is okay for now, you may close it at your convenience.

respectfully,
Dave M

**Comment by William1Neil** [comment]
Once again I thank you for the quick response. I'm using Vs 6.16.
All is working well.
