### ISSUE TITLE
clamd.conf not found

### ISSUE THREAD

**Issue by mdavies5** [dave-theunsub/clamtk#41]
V5.14. Every time I run clamtk from a script I get an error message in the terminal:
"ERROR: NotifyClamd: Can't find or parse configuration file /etc/clamav/clamd.conf".
/etc/clamav does contain freshclam.conf so I tried renaming this but the message persists. I have now created a new empty file clamd.conf but cannot test until an update is required. I cannot imagine it will solve the problem as it is a blank file.

Here is my script file:
#!/bin/bash
echo "Updating clam..."
freshclam --datadir=/home/michael/.clamtk/db --log=/home/michael/.clamtk/db/freshclam.log --user=michael
echo "clam updated"
exit

**Comment by dave-theunsub** [comment]
Hi,

Is this a ClamTk or ClamAV issue?  ClamTk doesn't use Clamd, and that's not a ClamTk scheduler file.
If you're not using ClamD, try removing that package and see if that helps.  Or if that error message is not stopping you from using the program, then you could always ignore it and move on.  It could also be that your freshclam.conf file is referencing clamd but you don't have it installed or configured.  You'll probably want your freshclam.conf, so I'd put that back too.

Thanks,
Dave M

**Comment by mdavies5** [comment]
Thanks Dave, It is a clamav issue. I am currently testing 2 new releases but in my default distro there is a clamd.conf. I think it is created by the command: dpkg-reconfigure clamav-base.
I must have forgotten to run it on the new installations.
Apologies, Michael
