### ISSUE TITLE
<SOLVED> Newbie question: How do I update the GUI?

### ISSUE THREAD

**Issue by bikrgran** [dave-theunsub/clamtk#43]
I am running Linux Mint 17 and have clamtk GUI 4.45.  It seems to keep up with the definitions and the av engine seems to be up to date, but I can't find any way to update the GUI.  I see that it's already past 5.1.  I'm fairly new to Linux, and not conversant with all the places to get stuff, but so far, all I've got is, "you already have this", but no way to UPDATE it.

Thanks!
Bikrgran

**Comment by dave-theunsub** [comment]
Hi Bikrgran,

Download the latest version here:
https://code.google.com/p/clamtk/

You'll want the "Debian or Ubuntu 13/14 DEB" link.  Just doubleclick it to update.  There is no in-program GUI updating yet.

Thanks,
Dave M

**Comment by bikrgran** [comment]
Thanks!  Got it!  I'd tried that before, but got some "error" message.  Piddled around and got it.  

Bikrgran

**Comment by dave-theunsub** [comment]
Thanks - closing

Thanks,
Dave M
