### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by AudioArchitect-R** [dave-theunsub/clamtk#45]
Here's a log of the error.
=================================
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 341369 files and directories currently installed.)
Preparing to unpack .../clamtk_5.18-1_all.deb ...
Unpacking clamtk (5.18-1) over (5.09-1~ubuntu14.04.1) ...
dpkg: error processing archive /home/multimedia/Downloads/clamtk_5.18-1_all.deb (--install):
 trying to overwrite '/usr/share/nautilus-python/extensions/clamtk.py', which is also in package clamtk-nautilus 5.09-1~ubuntu14.04.1
dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
dpkg-deb (subprocess): cannot copy archive member from '/home/multimedia/Downloads/clamtk_5.18-1_all.deb' to decompressor pipe: failed to write (Broken pipe)
dpkg-deb: error: subprocess <decompress> returned error exit status 2
=================================
Since I'm new to Linux I have no idea how to proceed.
Any help would be greatly appreciated.

Thank You!

**Comment by dave-theunsub** [comment]
Hi,

The Debian packagers and I package things differently - so pick one or the other.  If you want to use the Debian one, don't do anything.  If you want to use the one I package, erase clamtk, and then install it again.

Let me know if you have further questions.

Thanks,
Dave M
