### ISSUE TITLE
hardware Bugs

### ISSUE THREAD

**Issue by nqu35e** [dave-theunsub/clamtk#46]
This very good software ClamTk 5.19 version, currently am having bug in my system,am using chaletOs this bug crate feke  system operating files (duplicate it ) and start preventing most system files operating normally.
what I always does it I uninstall the software and install it again. an it work well. after scanning the system files and quarantined it, it can not be analysed save and  sent, it simply saying try again later, will there be another simple way of submitting report, it important this hardware problem  spoiled internet explore and now finding its way to linux.
am not very good at computer but can easily spot what is wrong

**Comment by dave-theunsub** [comment]
I haven't heard back in a while - please open with more information if need be.

Thanks,
Dave M
