### ISSUE TITLE
Recursive setting doesn't work

### ISSUE THREAD

**Issue by ineuw** [dave-theunsub/clamtk#47]
Trying to scan the media directory which includes my Windows drives, Linux drives and the Xubuntu home folder, but the recursive setting ignores them. I am the admin, this is a single user installation and I own all the drives. In addition, every advertised link to ClamTK leads back to the archived Google code page.

The installed front end is currently 5.11 which informs the user that a newer version is available, and any search leads back to the archive page again. If an update exists, where is it?

**Comment by dave-theunsub** [comment]
Sorry about the problems.  Here's what happened: Google Code froze its pages so I cannot use them or update them any longer.  Until we find a new landing page, start here:

https://github.com/dave-theunsub/clamtk/wiki

There are downloads links there for 5.20.  Note that only one thing (besides language files) changed - the right-click context menu has been removed.  If you want that, pick out the appropriate "add-on" on the downloads page.

Next - please do NOT scan Windows drives with ClamTk... it is not tested to work there.

Finally, tell me more about the recursive scan problem.  You may have to enable the scan hidden files/drives area in Settings as well.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
Ok, closing for now - open a new one if the problem persists.
