### ISSUE TITLE
Authorization asked for each file

### ISSUE THREAD

**Issue by eslogan** [dave-theunsub/clamtk#48]
Hi everyone!
I'm using Clam TK 4.41 in Linux Huayra 3.1 (Linux Huayra is an OS made by Argentinian Science and Technologies Ministry on the bases of Debian Jessie and MATE environment, it has mostly GNU GPL licencies, and this its official homepage is: http://huayra.conectarigualdad.gob.ar/huayra). 
It works pretty well except for two issues:
> I can't install an actualized graphic interface. I have tried using the software centre, and also using terminal instructions, but I couldn't get it done.
> This might be related to the previous issue: After analysis, ClamTK asks for confirmation to delete/quarantine each infected file. This gets really annoying, as it finds more than a thousand infections, and I'm forced to give authorization, one by one, clicking in a merging window. 
I guess there's a more actualized interface which offers the option to take the same action to every infected file, but, as I explained previously, I can't get to download and install it.

Thanks for attention, I hope you can can help me, so to keep using ClamTK.

**Comment by dave-theunsub** [comment]
Hi,

Is the installation problem with ClamTk, or are you wondering if ClamTk broke the installation of a different program?

Also, please DO NOT just quarantine or delete files.  First, disable PUA scanning in the Settings.  I guarantee (correct me if I'm wrong) all the detected files have "PUA" somewhere in the title, right?  That means they're "possibly unwanted applications".  So, again, please disable PUA scanning.  I'm planning to remove it from the 6.xx series altogether.

Yes, I could probably add a "quarantine all" or "delete all" button - but that would be a mistake.  If you think you have thousands of malicious files on your system, you have much bigger problems.  :)

Anyway, please let me know if I'm way off base or if I'm missing what you require help with.  I'm happy to answer other questions.

respectfully
Dave M

**Comment by eslogan** [comment]
Thanks, Dave! You must be right, most of my detected infections must be PUA, as it's not probable to find so many viruses in a single windows partition! But this leads me to the first problem again, as my interface doesn't show the option "PUA scanning" In settings window. My problem might be just due my inexpertice; I don't find the way to download and install a new interface. I have tried some time ago following some terminal instructions, but it seemed to get stacked at half-installation.

Thanks for this fast and clear answer!

-----Mensaje original-----
De: "Dave M" <notifications@github.com>
Enviado el: ‎20/‎10/‎2015 18:33
Para: "dave-theunsub/clamtk" <clamtk@noreply.github.com>
CC: "eslogan" <lisandroamado@gmail.com>
Asunto: Re: [clamtk] Authorization asked for each file (#48)

Hi,
Is the installation problem with ClamTk, or are you wondering if ClamTk broke the installation of a different program?
Also, please DO NOT just quarantine or delete files. First, disable PUA scanning in the Settings. I guarantee (correct me if I'm wrong) all the detected files have "PUA" somewhere in the title, right? That means they're "possibly unwanted applications". So, again, please disable PUA scanning. I'm planning to remove it from the 6.xx series altogether.
Yes, I could probably add a "quarantine all" or "delete all" button - but that would be a mistake. If you think you have thousands of malicious files on your system, you have much bigger problems. :)
Anyway, please let me know if I'm way off base or if I'm missing what you require help with. I'm happy to answer other questions.
respectfully
Dave M

**Comment by eslogan** [comment]
I have found some information about downloading and installing in your github page, I'll try again and then tell you if succeeded!

-----Mensaje original-----
De: "Dave M" <notifications@github.com>
Enviado el: ‎20/‎10/‎2015 18:33
Para: "dave-theunsub/clamtk" <clamtk@noreply.github.com>
CC: "eslogan" <lisandroamado@gmail.com>
Asunto: Re: [clamtk] Authorization asked for each file (#48)

Hi,
Is the installation problem with ClamTk, or are you wondering if ClamTk broke the installation of a different program?
Also, please DO NOT just quarantine or delete files. First, disable PUA scanning in the Settings. I guarantee (correct me if I'm wrong) all the detected files have "PUA" somewhere in the title, right? That means they're "possibly unwanted applications". So, again, please disable PUA scanning. I'm planning to remove it from the 6.xx series altogether.
Yes, I could probably add a "quarantine all" or "delete all" button - but that would be a mistake. If you think you have thousands of malicious files on your system, you have much bigger problems. :)
Anyway, please let me know if I'm way off base or if I'm missing what you require help with. I'm happy to answer other questions.
respectfully
Dave M

**Comment by dave-theunsub** [comment]
Hi again,

I also recommend you do not use this with a Windows computer.  I do not test it there... you should probably use a Windows antivirus to scan a Windows computer.

respectfully
Dave M

**Comment by eslogan** [comment]
Ok! Good advice! I'll use some portable windows anti malware, as my windows partition works really slowly. Thanks you very much, excellent attention!

-----Mensaje original-----
De: "Dave M" <notifications@github.com>
Enviado el: ‎21/‎10/‎2015 05:15
Para: "dave-theunsub/clamtk" <clamtk@noreply.github.com>
CC: "eslogan" <lisandroamado@gmail.com>
Asunto: Re: [clamtk] Authorization asked for each file (#48)

Hi again,
I also recommend you do not use this with a Windows computer. I do not test it there... you should probably use a Windows antivirus to scan a Windows computer.
respectfully
Dave M
