### ISSUE TITLE
clamtk 19.1 crashes in xubuntu 15.10

### ISSUE THREAD

**Issue by Pastim** [dave-theunsub/clamtk#49]
Hi,

I recently upgraded my xubuntu laptop from 15.04 to15.10.  clamtk_5.19-1_all.deb  no longer runs.

I'm no linux expert so don't know how to diagnose the problem.  The syslog reports:

Oct 27 08:33:22 twpsamlinux kernel: [ 2663.742339] traps: clamtk[5026] trap invalid opcode ip:7fd788a6e168 sp:7fff948b1f88 error:0 in libcrypto.so.1.0.0[7fd7889ca000+21c000]
Oct 27 08:34:14 twpsamlinux whoopsie[803]: [08:34:14] Parsing /var/crash/_usr_bin_clamtk.1000.crash.
Oct 27 08:34:14 twpsamlinux whoopsie[803]: [08:34:14] Uploading /var/crash/_usr_bin_clamtk.1000.crash.
Oct 27 08:34:16 twpsamlinux whoopsie[803]: [08:34:16] Sent; server replied with: No error
Oct 27 08:34:16 twpsamlinux whoopsie[803]: [08:34:16] Response code: 200
Oct 27 08:34:16 twpsamlinux whoopsie[803]: [08:34:16] Reported OOPS ID 81798be0-7c85-11e5-bddc-fa163e75317b

The clamav update seems to work, although the log is full of issues.  I can't attach that (I don't have write permission to this repositoy), but a sample is below.  I get loads of the DNS failures and saving PID failures.

Tue Oct 27 08:01:05 2015 -> ClamAV update process started at Tue Oct 27 08:01:05 2015
Tue Oct 27 08:01:05 2015 -> main.cvd is up to date (version: 55, sigs: 2424225, f-level: 60, builder: neo)
Tue Oct 27 08:01:06 2015 -> Downloading daily-21014.cdiff [100%]
Tue Oct 27 08:01:07 2015 -> Downloading daily-21015.cdiff [100%]
Tue Oct 27 08:01:21 2015 -> daily.cld updated (version: 21015, sigs: 1633568, f-level: 63, builder: neo)
Tue Oct 27 08:01:22 2015 -> bytecode.cld is up to date (version: 268, sigs: 47, f-level: 63, builder: anvilleg)
Tue Oct 27 08:01:31 2015 -> Database updated (4057840 signatures) from db.local.clamav.net (IP: 172.110.204.67)
Tue Oct 27 08:01:31 2015 -> --------------------------------------
Tue Oct 27 08:39:06 2015 -> Update process terminated
Tue Oct 27 08:39:25 2015 -> --------------------------------------
Tue Oct 27 08:39:25 2015 -> ERROR: Can't save PID to file /var/run/clamav/freshclam.pid: No such file or directory
Tue Oct 27 08:39:25 2015 -> freshclam daemon 0.98.7 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
Tue Oct 27 08:39:25 2015 -> ClamAV update process started at Tue Oct 27 08:39:25 2015
Tue Oct 27 08:39:25 2015 -> WARNING: Can't query current.cvd.clamav.net
Tue Oct 27 08:39:25 2015 -> WARNING: Invalid DNS reply. Falling back to HTTP mode.
Tue Oct 27 08:39:25 2015 -> Reading CVD header (main.cvd): Tue Oct 27 08:39:25 2015 -> WARNING: Can't get information about db.local.clamav.net: Temporary failure in name resolution
Tue Oct 27 08:39:25 2015 -> WARNING: Can't read main.cvd header from db.local.clamav.net (IP: )
Tue Oct 27 08:39:25 2015 -> Trying again in 5 secs...
Tue Oct 27 08:39:30 2015 -> ClamAV update process started at Tue Oct 27 08:39:30 2015
Tue Oct 27 08:39:30 2015 -> main.cvd is up to date (version: 55, sigs: 2424225, f-level: 60, builder: neo)
Tue Oct 27 08:39:30 2015 -> daily.cld is up to date (version: 21015, sigs: 1633568, f-level: 63, builder: neo)
Tue Oct 27 08:39:30 2015 -> bytecode.cld is up to date (version: 268, sigs: 47, f-level: 63, builder: anvilleg)

**Comment by Pastim** [comment]
I tried version 5.2, and cloned the github current version, both of which crash in the same way.

I also found a bug reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793557 which seems to be the same as the problem I have encountered.

The 15.10 upgrade changed a load of libraries.  Whether libssl1 was one I can't be sure.

I'll be happy to do more research into what's going on, but I don't know what's needed, not how to provide it .  I have some crash dumps in /var/crash but can't post them here.

**Comment by dave-theunsub** [comment]
Well that's interesting.  Thanks for pointing out the Debian bug as well -
I was not aware of that.  I'll do some more investigation when I get home
and will post back.

respectfully
Dave  M

**Comment by Pastim** [comment]
I sent a crash dump file you your email address.

**Comment by dave-theunsub** [comment]
Hi,

I installed a fresh Ubuntu 15.10 in Virtualbox and installed version 5.20 ClamTk - all is well here.  I can't duplicate this issue.  Xubuntu should be the same, right?  Also, in a fully patched Debian 8 (also in Virtualbox), everything is working just fine. I'm not sure where to go with this... if I can't duplicate it I can't fix it.  Hopefully we can get more information - maybe from the Debian post...

respectfully
Dave M

**Comment by Pastim** [comment]
Did the crash dump not show anything?

I suspect there is a library mismatch or some such as a result of the upgrade from 15.04.  When I installed 15.10 a lot of older libraries were deleted.

**Comment by dave-theunsub** [comment]
Yes, I've seen it, and I've seen similar issues reported with other programs, but no solutions yet.  It may be something with the upgrade.  Can you try reinstalling libcrypt-ssleay-perl?

respectfully
Dave M

**Comment by Pastim** [comment]
libcrypt-ssleay-perl was not installed.  It is now, but it made no difference.  This makes me wonder if the dependencies have been broken during the upgrade.  I have already uninstalled and reinstalled clamtk.  Should I do the same with clamav?

**Comment by dave-theunsub** [comment]
I wouldn't think that would matter, but let's give it a shot. :)

respectfully
Dave M

**Comment by Pastim** [comment]
I reinstalled clamav (and base, clam library etc). clamscan runs OK (it probably did before but I hadn't tried that).  clamtk still crashes.  

The library you mentioned - should that have been installed or not?

**Comment by dave-theunsub** [comment]
I think you can erase it - it shows up in the log you sent, looked like reinstalling might help.

**Comment by Pastim** [comment]
OK - thanks.  A mystery then.  

I looked at the 'software centre' list of updates for the upgrade, but it seems that not all upgrade info is logged in the same place.  In the limit I could install 15.10 clean, but I'd rather not for now.

**Comment by dave-theunsub** [comment]
Sorry, I'm at a loss... I don't know how to duplicate the problem here, and I'm not sure what the crash log you sent is reporting.  If you get any other information, please pass it along and I'll do my best.  Additionally, I'll keep an eye on the Debian bug you linked to - maybe they'll come up with an answer for us.

respectfully
Dave M

**Comment by Pastim** [comment]
Is there some (x)ubuntu processing I could do on the crash log to make it more helpful?

**Comment by dave-theunsub** [comment]
Probably not.  I don't think it will get any easier.  :|

I'd recommend reinstalling Perl itself, but I'm afraid of borking your system.  I'll post back if I think of anything else.

respectfully
Dave M

**Comment by Pastim** [comment]
Would installing the debug version of libssl help?

**Comment by dave-theunsub** [comment]
That I do not know.  I don't think it would hurt anything though.

**Comment by Pastim** [comment]
I thought it might enhance the crash log.  I'll give it a try later today - other stuff to do now.

Regards

Tim

**Comment by Pastim** [comment]
Looking through the debian bug report, this bodge seems to work,.  I have no idea why :)

OPENSSL_ia32cap=0 clamtk

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793557;msg=57

Tim

**Comment by dave-theunsub** [comment]
Neither do I... I'm not familiar with that wizardry... My concern here is we don't know what's really causing the issue, right? Is there some kind of library mismatch going on (for example) for people who upgraded rather than did a fresh install or something?  I mean, I can't duplicate the problem with a fresh install, and I haven't received any other hate mail on this, so it can't be too widespread...

respectfully
Dave M

**Comment by Pastim** [comment]
Well there's a way round it for simple folk such as myself, so I'm happy enough now, and if others have the same problem you can at least give them this work-around.

I trust there'll be no 'hate mail' or similar aimed at you (or indeed anyone). The behaviour of most of the linux community sometimes helps me to keep some faith in humanity, although I may have been lucky (so far!).

**Comment by Pastim** [comment]
This is not a clamtk bug.  The Debian folk claim it's fixed in ssl on Debian.  It isn't fixed in xubuntu 15.10 (wily) so I still have to use the workaround I mentioned earlier.

If it's useful to close this here, please do so.  I don't want to close it myself in case you think leaving it open might help other people encountering the same problem.

**Comment by dave-theunsub** [comment]
Closing based on https://github.com/dave-theunsub/clamtk/issues/49#issuecomment-191242372
