### ISSUE TITLE
Whitelist box doesn't accept any input .....

### ISSUE THREAD

**Issue by Spazum** [dave-theunsub/clamtk#50]
I clicked in the Whitelist interface, and no text caret appears to enter information. It doesn't seem to respond to anything, mouse clicks or TAB curser. The only element that functions, is the BACK button.

Also why does the status text on the bottom bar never change from "An update is available" ?
I clicked the Update Assistant and highlighted the button "my computer automatically receives updates".

I clicked the Update and it says "Your are already configured to automatically receives updates".

**Comment by dave-theunsub** [comment]
Hi,

The Whitelist interface expects you to click on Add or Delete buttons for
adding or deleting directories which should be whitelisted.

The "Update is available" refers to the GUI interface - which you can
download from the Downloads link:

https://github.com/dave-theunsub/clamtk/wiki

The Update button refers to signatures, not the GUI.

In retrospect, that part might be confusing.  I'll think about how to make
it less confusing...

respectfully
Dave M

**Comment by Spazum** [comment]
Thanks Dave, another question so I am to assume that the Whitelist interface will "popup" a new interface which includes a "ADD or DELETE" button or list? Because this is not the case ... srryy to be such a critic ....

**Comment by dave-theunsub** [comment]
Hi,

There should be a row at the bottom, above the Back button area, with "Add"
or "Delete".  They aren't there?  If they aren't there, are you using a
custom icon theme?  Try temporarily switching icon themes and see if they
show up then.

respectfully
Dave M

**Comment by Spazum** [comment]
Dave I changed my Mint 13 Cinnamon 64-bit Systems Settings - Themes - to Default then I rebooted. Seems that those are not appearing. Here is a screenshot ......
![screenshot from 2015-10-27 11 04 58](https://cloud.githubusercontent.com/assets/15344208/10762097/e9f29ec2-7c9a-11e5-8a18-82a5d977033d.png)

**Comment by dave-theunsub** [comment]
Hi,

Are you using the legacy version or the main version?  That looks like the
legacy version, intended for the 12.xx series of Debian (and its
derivatives).  You should be able to use the main version.  Try that and
see what happens.

Also, can you open a terminal window and type "clamtk" (no quotes) - let's
see if there are any error messages popping up.

respectfully
Dave M

**Comment by Spazum** [comment]
Your right, Dave I might have downloaded the legacy version, and installed it thinking that it was "universal" and would have replaced the older GUI which was 4.XX. I opened  using the terminal and it didn't complain .... so i'll uninstall this Clamtk then reinstall using the main version.

**Comment by Spazum** [comment]
Considering the fact that Cinnamon Mint still has the older versions 4.XX using the Software Manager, and Clamtk's "Unofficial/Other" link shows only  "Isadora" thru "Qiana" compatible version  download  links, I'm not surprised to see this error when I tryed installing the Main version ............

Error: Dependency is not satisfiable: libgtk2-perl (>= 2:1.241)

My Cinnamon is obsolete or needs updated software which im not for certain how I can fix that problem -.-

**Comment by dave-theunsub** [comment]
Hmmm... that might be the problem, I'm not sure.  I don't have a lot of experience with Mint.  Is there a Mint forum somewhere that might be able to figure this out?  

And yes, you'd probably have to stick with the legacy version for now - until you update.

respectfully
Dave M
