### ISSUE TITLE
Update version number on clamtk.sourceforge.net

### ISSUE THREAD

**Issue by jamesbroadhead** [dave-theunsub/clamtk#56]
The website says that the latest version is 5.00 :)

Alternately, [move the website off sourceforge](
http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/) & move releases to github, which would be less surprising than the split between sourceforge, bitbucket & github. 

I'd advise that the github README should have a note about the website, the release location and the repo.

**Comment by dave-theunsub** [comment]
James,

Thanks for the much needed advice.  Once we lost the Google code site, there was mass confusion.  I've been considering using one of my own domains or using a Google sites or blogspot or ... lots of options but I haven't done any of them.  For now, there are:

https://github.com/dave-theunsub/clamtk
https://github.com/dave-theunsub/clamtk-gtk3
https://bitbucket.org/dave_theunsub/
https://launchpad.net/clamtk

Still haven't pushed gtk3 version yet, either.  Maybe a good solution for now is to use the launchpad site...

Good points though.  I need to stop delaying and just do it.

**Comment by jamesbroadhead** [comment]
Other projects have success with these: https://pages.github.com/ 

Thanks for clamtk! :)

**Comment by dave-theunsub** [comment]
Looks nice - I'll check it out today.

Thanks James.

v/r,
Dave M
