### ISSUE TITLE
Restoring a quarantined file doesn't work

### ISSUE THREAD

**Issue by AXDOOMER** [dave-theunsub/clamtk#57]
I'm trying to restore a quarantined file to send it to VirusTotal so I can see if I really got infested by a virus.

When I save the file, it doesn't appear. I saved it on my desktop, it didn't work. I can't see it. I saved it in a folder and displayed hidden files, it still wasn't there. The size of the folder is 0 bytes. 

I have ClamTK 5.11. This is the latest version that works on my system.

**Comment by AXDOOMER** [comment]
Also, there should be a way to submit a quarantined file for analysis.

**Comment by dave-theunsub** [comment]
@AXDOOMER ,

Sorry, this one got lost in the shuffle.  Are you still having this issue?

Thanks,
Dave M

**Comment by AXDOOMER** [comment]
Yes. I have ClamTK 5.11.

**Comment by dave-theunsub** [comment]
@AXDOOMER ,

Can you try upgrading to 5.21 and see if the problem persists?

Download links:
http://dave-theunsub.github.io/clamtk/

Thanks,
Dave M

**Comment by AXDOOMER** [comment]
It works! Thanks.
