### ISSUE TITLE
Clamtk-gnome multifiles scan

### ISSUE THREAD

**Issue by Paviluf** [dave-theunsub/clamtk#58]
Hello,

It's not possible to select and scan multiple files and directory at once with clamtk-gnome. Can it be add please ? It seem that it was possible before.

https://bitbucket.org/dave_theunsub/clamtk-gnome/

Thanks !

**Comment by dave-theunsub** [comment]
Hi Paviluf,

I'll take a look at it and see if it is feasible.

Thank you for letting me know.

respectfully
Dave M

**Comment by sniper1720** [comment]
hello
+1 . it will be a great addition.
and i just want to say thanks for the program.
best regard.
Djalel.

**Comment by dave-theunsub** [comment]
@Paviluf @sniper1720 ,

Please re-open this over on the clamtk-gnome side:

https://github.com/dave-theunsub/clamtk-gnome/issues

@SunyataZero  is already looking into making this happen.

Thanks, sorry to be difficult. :)

Thanks,
Dave M

**Comment by Paviluf** [comment]
Done. https://github.com/dave-theunsub/clamtk-gnome/issues/3
