### ISSUE TITLE
Clamtk don't detect virus on subdirectory 'subfolder' archive (zip..etc)

### ISSUE THREAD

**Issue by sniper1720** [dave-theunsub/clamtk#59]
hello 
before i post the issues 'thanks'
to comprehend the problem i will post it on details so :
i create a folder with subfolder and i put a virus ( 'eicar.com.txt') on the subfloder than i **compress** the folder and scan it with clamtk & clamtk-nautilus and it detect nothing.
1-i enable all features on setting except scan for puas 
2-it detect the file as virus when scan directly or when put it on main folder of archive.
so it like this : `archive/virus`(the virus compressed then scaned) : **detected**
`archive/virus+folder` (the same level ) **not detected** 
`archive/folder/virus` : **not detected** .
**I thinks this is a serious problem.** 

**N.B** : i run clamav from the terminel : `clamscan --scan-archive=yes --recursive=yes --max-files=3000 --max-recursion=30 --max-dir-recursion=30 --max-filesize=500M --max-scansize=500M filename` and it detect the virus in the 3 case & in the fourth case too : `archive/folder/subfolder/virus`

if you need more information you are welcome .

respect & peace!
Djalel.

**Comment by dave-theunsub** [comment]
Hi Djalel,

Thank you - let me take a look at it and see what I can do.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
Djalel,

If I add --scan-archive=yes, that should solve it, right?  Seems okay from my end.  I'll add it to 5.21.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
5.21 is out. Give it a shot.

respectfully
Dave M

**Comment by sniper1720** [comment]
great and fast job
i will give it a try and tell you 
best regard.
Djalel.

**Comment by dave-theunsub** [comment]
@sniper1720 ,

Can you explain this one a little more?  I'm not sure I understand the difference between the examples you have above.

respectfully
Dave M

**Comment by sniper1720** [comment]
Yes i can explain :) : now it scan archives but it limit to the archive size : what i mean is when i scan an archive of 25 MB it detect the virus but in archive of 98 MB it not detect the virus ; i think in the second case it skip the archive scan due to the size.

hope that i explain the problem
Best regards
Djalel.

**Comment by dave-theunsub** [comment]
@sniper1720 

Can you see if 5.21 fixed the problem?

https://dave-theunsub.github.io/clamtk/

Thanks,
Dave M

**Comment by sniper1720** [comment]
hello again
@dave-theunsub 
the problem above is with clamtk 5.21 ( the same with 5.20).

Regard
Djalel.

**Comment by dave-theunsub** [comment]
@sniper1720 

Ok, I think I still need to add the "max-scansize=x" option... I'll add it to 5.22.

Thanks,
Dave M

**Comment by dave-theunsub** [comment]
Closing for now. Open a new ticket if this is still an issue and we can re-engage.
