### ISSUE TITLE
Google top result is Sourceforge

### ISSUE THREAD

**Issue by majorbob** [dave-theunsub/clamtk#60]
When searching for ClamTK, the top 4 results in Google search are clamtk.sourceforge.net pages.  But that page was last updated in 2013 so the project looks like it is dead.  Are you able to add a message on that page that says the project has now moved to https://dave-theunsub.github.io/clamtk/
?

**Comment by dave-theunsub** [comment]
Hi @majorbob 

I'm kind of lost too... :)  I say that to be funny, but if someone asked me right now, I couldn't point to its home page. Technically, ClamTk is kind of homeless right now.  I did not prepare adequately for ClamTk post Google Code.  Anyway, I'm working on it, but none of the sites I see look like where I want to stick ClamTk.  Google Code was perfect for it.

Unfortunately I can't change Google results, but we can find a home for ClamTk anyway.  I'll keep looking.

Thanks,
Dave M

**Comment by majorbob** [comment]
Hi Dave, what is wrong with github.io ?  It just has to be any page that links to downloads, source & bug reporting.  Do you still have access to the Sourceforge account to update pages?
I am happy to help if you need.
Thanks for your work & replies.

**Comment by dave-theunsub** [comment]
@majorbob 

Thanks for the inputs - I have placed a redirect on the SF site so visitors there will go to the github.io site.  I think once the search engines pick up the redirect it may help.

Closing for now, - we'll reopen if need be.

Thanks,
Dave M
