### ISSUE TITLE
Directories not scanning if users home includes /sys or /dev

### ISSUE THREAD

**Issue by majorbob** [dave-theunsub/clamtk#61]
Took me a while to figure out why Directory scanning would not work for me at all - always reported 0 files and 0 directories scanned, even with eicar test file.

I worked out it was due to my username. Because /sys, /dev and /proc are all white-listed in /usr/share/perl5/ClamTk/App.pm, if the user home path contains those strings then it is excluded from the scan completely. For example the following users would not be able to scan anything in their home directory:
````
/home/sysmgr (contains /sys)
/home/developer (contains /dev)
/home/procar (contains /proc)
````
Technically this is actually a bug in ClamAV, but I suspect it will take longer to fix there. We can work around their bug by adding the trailing forward slashes, changing App.pm, line 484 to:
````
        = join( ';', $path->{ viruses }, '/sys/', '/dev/', '/proc/;' );
````

**Comment by dave-theunsub** [comment]
@majorbob ,

Thanks, I think you're right.  I'll have a look and, assuming it is right, will put the fix in 5.22.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
@majorbob ,

Are you up for testing 5.22 to ensure it works for you?

respectfully
Dave M

**Comment by majorbob** [comment]
Update tested successfully.  
Thanks Dave,
