### ISSUE TITLE
Port clamtk-kde to KDE/Plasma 5

### ISSUE THREAD

**Issue by Paviluf** [dave-theunsub/clamtk#62]
Hello,

It will be great if clamtk-kde could be ported to KDE/Plasma 5.

https://bitbucket.org/dave_theunsub/clamtk-kde

Thanks !

**Comment by dave-theunsub** [comment]
Ok, as far as I can tell, I just have to change the requirement to kf5-filesystem and drop the desktop file into a different directory.  Building for Fedora is easy - I have to hope I still have the build scripts for Debian and Ubuntu...

Anyhoo, hopefully I can get this out in a day or two.

Thanks,
Dave M

**Comment by Paviluf** [comment]
Awesome ! Thank you !

**Comment by dave-theunsub** [comment]
Ok, it's done.  Closing out for now.

Thanks for the heads up - I should've done that a long time ago.

https://dave-theunsub.github.io/clamtk/

Thanks,
Dave M
