### ISSUE TITLE
Clamtk-kde multifiles scan

### ISSUE THREAD

**Issue by Paviluf** [dave-theunsub/clamtk#63]
Hello,

Like for [Clamtk-gnome](https://github.com/dave-theunsub/clamtk/issues/58) it's not possible to select and scan multiple files and directory at once with clamtk-kde. It will be great if it can it be add ! It seem that it was possible before.

Thanks !

**Comment by dave-theunsub** [comment]
Hi @Paviluf ,

I'm going to close this here - please open it on the clamtk-kde site (link below).  Sorry, there's no real official way for us to move it... :(   But the upside is you get to post the first official clamtk-kde bug!  :)

We're looking at adding this functionality to both gnome and kde.

https://github.com/dave-theunsub/clamtk-kde/issues

Thanks,
Dave M

**Comment by Paviluf** [comment]
Done. https://github.com/dave-theunsub/clamtk-kde/issues/1

**Comment by dave-theunsub** [comment]
Thanks @Paviluf !  Like I said, @SunyataZero and I are working on clamtk-kde and clamtk-gnome, so hopefully we can get this functionality working.

Thanks,
Dave M
