### ISSUE TITLE
I can not set a scan daily in clamtk

### ISSUE THREAD

**Issue by mislao** [dave-theunsub/clamtk#65]
I can not set a scan daily. The program is not responding. What should I do?

**Comment by dave-theunsub** [comment]
Hi,

Can you give more details?  What version are you using?  What operating system?

Thanks,
Dave M

**Comment by mislao** [comment]
I have Linux Antergos. Clamtk 5.22-1.

**Comment by dave-theunsub** [comment]
Ok, try this:

1. Open a terminal window (gnome-terminal or whatever) and type "clamtk" (no quotes).
2. Try to set a daily scan again.
3. If there's anything on the terminal screen, copy and paste it in a reply here.

Also, when you exit ClamTk, go back to the terminal window, and type "crontab -l" (no quotes).  That's a lowercase "L" not a 1 (one).

Thanks,
Dave M

**Comment by mislao** [comment]
Thanks :)

**Comment by mislao** [comment]
`$ clamtk
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
problem checking crontab listing in is_enabled
Error opening crontab in remove: Broken pipe
Error opening crontab command in apply_scan: Broken pipe

`

**Comment by dave-theunsub** [comment]
> I have Linux Antergos
I'm not sure what this is, but can you ensure crontab is installed and operating correctly?  This looks more like a crontab issue than ClamTk.

Also, what is the output of "crontab -l" ?  (that's a lowercase L)

Thanks,
Dave M

**Comment by mislao** [comment]
I had to install a crontab, because it was not. Now everything is OK. Thanks


Wojtek


W dniu 16.10.2016 o 15:02, Dave M pisze:
