### ISSUE TITLE
download and signature unavailable

### ISSUE THREAD

**Issue by anthraxx** [dave-theunsub/clamtk#74]
looks like the official downloads are gone, leading to 404:
https://bitbucket.org/dave_theunsub/clamtk/downloads/clamtk-5.24.tar.gz
actually it seems to affect the whole space: https://bitbucket.org/dave_theunsub/clamtk

**Comment by dave-theunsub** [comment]
Thanks for letting me know!  It should be back now.  Closing.

Thanks,
Dave M

**Comment by anthraxx** [comment]
thx, works
