### ISSUE TITLE
missing git release tags

### ISSUE THREAD

**Issue by anthraxx** [dave-theunsub/clamtk#75]
It seems there are no tags in the git tree. It would be quite handy if the tags could be kept in sync so upstream watches could easily be setup and releases can be easily linked to a git commit

**Comment by dave-theunsub** [comment]
Is there a project you can point me to so I can see an example?

Thanks,
Dave M

**Comment by anthraxx** [comment]
literally every project has such, picking randomly one: https://github.com/mesonbuild/meson/releases

**Comment by dave-theunsub** [comment]
It's been a year, so I should get back to this one. (sorry for the delay and attempt at humor)

I've never used github as a release mechanism, nor have I ever used tags with git. Github has been used mainly for a splash [page](https://dave-theunsub.github.io/clamtk/) and an extra repo for hosting code.  The tags seem like an okay idea, and I'll consider that for upcoming releases.

Thanks,
Dave M
