### ISSUE TITLE
Scheduler does not seem to work for Ubuntu 16.04 w/ clamtk 5.20

### ISSUE THREAD

**Issue by mdwy62** [dave-theunsub/clamtk#76]
Hi Dave M - the ubuntu 16.04 repository version of clamtk is 5.20. The scheduler only seems to be able to schedule a midnight run. My pc is usually asleep then. When I click on the "-" to remove this, I get the "+" sign. I enter 22 into the hour box for 10pm and click the "+" sign. I am told "a daily scan is scheduled". Unlike the antivirus signature dialog though, the hour has reverted to "0". 

When I look in ~/.clamtk/cron, I see 0 0 * * * /usr/bin/clamscan 
even after I close the scheduler and clamtk. 

/var/spool/cron/crontab/<username> shows that clamtk wrote it successfully, but it has the midnight entry: 0 0 * * * /usr/bin/clamscan

Also while I am here, is there a way to pass nice and ionice parameters to the job?

Thanks.

\- Mark D

**Comment by dave-theunsub** [comment]
Hi Mark,

I just tried to schedule scans at different times and all worked as expected.  Note that you can just type "crontab -l" (<- lowercase L) to list your cron jobs.

Can you try upgrading to see if that fixes the issue?

You can get newer versions here:
https://dave-theunsub.github.io/clamtk/

or, more directly, for version 5.24:
https://bitbucket.org/dave_theunsub/clamtk-legacy/downloads/clamtk_5.24-1.legacy_all.deb

You should be able to just double-click it to install.

Also, try running ClamTk from the commandline - open a terminal window and type "clamtk" (no quotes), and try to schedule scans.  Maybe there's an error message that will show up in the terminal window to help us.

Thanks,
Dave M

**Comment by mdwy62** [comment]
Hi Dave.

Thanks for crontab -l. 

1) I tried running 5.20 in gnome-terminal. No output in the terminal and the same behavior. 
2) I wanted the repository version to work, so I uninstalled and reinstalled, but same behavior. 
3) I installed 5.24. I then first deleted the entry for antivirus signatures in the scheduler dialog. 
Doing this, I was able to get the clamav entry to stick. But now I cannot make an entry for signatures, though I still get the message: "you are set to automatically receive updates". 
4) I thought this might be because under settings I have "Check for updates to this program checked". But when I remove (uncheck) that, the scheduler dialog still says "you are set to automatically receive updates". 
5) crontab -l now just shows the clamscan entry, not a freshclam entry. Currently I have signatures 22937, is that current? If so, is freshclam not needed (since I don't see a crontab entry for it)?

Thanks.
- Mark

**Comment by dave-theunsub** [comment]
Hi Mark,

If you'd like to update signatures yourself - using the scheduler or not - use the Update Assistant to select that option.  Some Linux distributions have it set up to automatically download signatures, so by default that is the option used.  However, that default option requires root privileges, so you won't have the option to update it or schedule it if you're not running as root.

The "check for updates to this program" is for the GUI, while the antivirus signatures is a different kind of update.

Thanks,
Dave M

**Comment by mdwy62** [comment]
Dave - Thanks for your patience. Right - now I get that I had Update Assistant set to automatic which is why I cannot schedule signature updates manually. Signatures are upating. Many thanks. - Mark
