### ISSUE TITLE
Updating clamtk 

### ISSUE THREAD

**Issue by Snarkly** [dave-theunsub/clamtk#77]
How do you upgrade to the newest version. I have version 4.45 but I can't figure out how to upgrade it. I've tried clicking on help, then check for updates but it still wont update clamtk. Here's a screenshot http://imgur.com/a/N6HiE I'm using Linux Mint Rosa.

**Comment by dave-theunsub** [comment]
Hi,

Download the latest version here:
https://dave-theunsub.github.io/clamtk/

You'll probably want this one:
https://bitbucket.org/dave_theunsub/clamtk/downloads/clamtk_5.24-1_all.deb

respectfully
Dave M

**Comment by Snarkly** [comment]
Thanks but what about the old version? Does this upgrade the old version or do I have to uninstall the old version before I install the new version. The version I have now I got through the software manager. And sorry for the dumb questions, I'm new to linux and still learning about it.

**Comment by dave-theunsub** [comment]
It will replace the old version; nothing to worry about.

respectfully
Dave M

**Comment by Snarkly** [comment]
Thanks, it seemed to install ok so I'll close this issue.
