### ISSUE TITLE
Suggestions as Request for Dave

### ISSUE THREAD

**Issue by pradeepkthomas** [dave-theunsub/clamtk#78]
Hi Dave,
Could not find your e-mail address, so joined GitHub.

I use ClamTK 5.20 on Lubuntu 16.04.2 LTS, and it works fine. I have mentioned this once earlier to you, but will request you again. 
The issue is : When I attach a pendrive used on a windows system loaded with virus and do a virus check on my computer with ClamTK 5.20, it discovers loads of PUA. The problem is there is no facility available in the scanner to select all the discovered PUA's (Say maybe 500+ of them) to delete them in one go. It is impractical to keep clicking each PUA to delete it or Quarantine it.

Please provide a button on the scanner to enable one to select all  or required files, that can be deleted in one go. Deleting 500+ files is time consuming and not practical.

My e-mail is pradeepthomas@bsnl.in, if you have any suggestions or feed back, please let me know what you think about my suggestion.
Appreciate what you are doing to make ClamTK freely available.
Thanks and God Bless.
Pradeep K. Thomas

**Comment by dave-theunsub** [comment]
Handled offline (email)
