### ISSUE TITLE
Clamtk Ver 5.xx will not come up on Linux Mint KDE 17.3 Ubuntu 14.04 

### ISSUE THREAD

**Issue by phd21** [dave-theunsub/clamtk#80]
Hi ClamTK (Dave?) Developers,

First, Thank You for providing this very nice GUI front-end and the addons for Clamav. I hope everyone involved keeps this maintained and up to date. Although Linux users really do not need an anti-virus anti-malware application often, it sure is nice to have one, just in case; and for interacting with users of MS Windows and Mac systems. 

I have tried installing "clamtk_5.24-1_all.deb" and the "clamtk_5.24-1.legacy_all.deb", and neither will come up. The ClamTK 4.45 version from the repositories works, but I cannot resize it. 

When I run ClamTK v5.24-1 from the console terminal prompt, I get the message below:
"Icon 'gtk-new' not present in theme at /usr/share/perl5/ClamTk/GUI.pm line 284."
When I run ClamTK v5.24-1 Legacy from the console terminal prompt, I get the message below:
"Icon 'gtk-new' not present in theme at /usr/share/perl5/ClamTk/GUI.pm line 315."

So, I ran "locate gtk-new" which found png and svg icons. I tried copying those to "/usr/share/perl5/ClamTk" which did not work? The .png file claims to be a  link (non-working) on my system? 

If I purge ClamTK 5.xx and install the one from the Linux Mint 17.x repos, it works again. But, I would like the new version.

FYI: I have "Linux Malware Detect (LMD)" also installed running in conjunction with ClamAV.

Best rergards,
Phil
phd21

**Comment by dave-theunsub** [comment]
Hi Phil,

This means that the theme you're using does not employ those icons.  If you switch to a different theme, it should work (assuming it has all those icons, of course!).

I recommend not using the older 4.xx series, as it has not been touched in quite a long time.

Thanks,
Dave M

**Comment by phd21** [comment]
Hi dave-theunsub,

Thank you for respondng. 
Why would this program be dependent upon any desktop theme? Should it not include any necessary icons in its install?

What theme in KDE would I choose?

Regards,
Phil
phd21

**Comment by dave-theunsub** [comment]
Hi Phil,

It is strange that a program wouldn't work because a particular theme doesn't have an icon.  It should show a "broken image" icon or something if it doesn't have it, I think.  I'm not sure how to make that happen.  If I ever get around to making version 6.x, maybe I can change that behavior.

I recommend giving a few themes a try.  Offhand I don't have a list or anything of themes that work.  Sorry, I don't have a better solution at present.

Thanks,
Dave M

**Comment by kujub** [comment]
Hi,

maybe the following helps a bit: 

I had the same Problem on CentOS 7 today and was able to fix it by simply installing a package called 'gnome-icon-theme-legacy' which appears to be a split out of 'gnome-icon-theme'.

RPM Package info:

> Name        : gnome-icon-theme-legacy
Arch        : noarch
Version     : 3.12.0
Release     : 1.el7
Size        : 0.0  
Repo        : installed
From repo   : base
Summary     : Old names for icons in gnome-icon-theme
License     : LGPLv3+
Description : This package contains symlinks to make the icons in gnome-icon-theme
            : available under old names.
>
Don't know about the DEB, but maybe the RPM should depend on that one?

Regards
Kurt B.

**Comment by dave-theunsub** [comment]
Hi Kurt,

Thank you for the additional information. 

You are correct; the Fedora builds used gnome-icon-theme-legacy but the CentOS builds (6 & 7) use gnome-icon-theme..

Ok, I'll work on fixing  the CentOS builds...

Thanks,
Dave M

**Comment by dave-theunsub** [comment]
Closing for now. If the issue persists, please open a new ticket or reopen this and I'll take a look again.

respectfully,
Dave M
