### ISSUE TITLE
antivirus signatures lockup

### ISSUE THREAD

**Issue by ampmaker** [dave-theunsub/clamtk#81]
Tried to update my antivirus signatures twice today. Previous signatures at 23453. It got as far as 23454 and then the program stopped and went gray in color and stopped updating. I waited  for about 3 minutes and had to reboot my computer. Both times I tried (about three hours apart) the same thing happened. I am running Ubuntu 16.04 LTS with all of the latest updates as of Saturday, June 3, 2017. My version of Clamtk is 5.24.

**Comment by dave-theunsub** [comment]
Hi,

That version number is not too far from the current (right now is 23459).  Sometimes the signature mirrors run a little slow, and that could cause this issue.

Try running ClamTk from the command line - just type "clamtk" (no quotes) and hit enter.  Then try to update.  If you see any errors or messages in the terminal window, please post them back here.

respectfully
Dave M

**Comment by ampmaker** [comment]
Dave,
I tried your suggestion using the command line. Ran the update. The update completed , but for some reason it took between 11 and 12 minutes to finish. Normally when the program goes gray it will complete in about 30 seconds.
Thanks for the suggestion. At least I know it is still working and I have filed this hint away for future use.
Hugh
