### ISSUE TITLE
ClamTk 5.25 not available for download

### ISSUE THREAD

**Issue by heynnema** [dave-theunsub/clamtk#84]
The changelog indicates that 5.25 was ready in February, but it's not available to download anywhere.

**Comment by dave-theunsub** [comment]
Hi,

Sorry for the misleading changelog; that was the start of a changelog for a new version which has not been released.  I do that so I keep track of what I've finished, and so users can see what I'm doing as well.

Long story short:  5.24 is still the latest.

respectfully
Dave M

**Comment by dave-theunsub** [comment]
Hi,

*Now* 5.25 is out.  :)

https://dave-theunsub.github.io/clamtk/

Thanks,
Dave M
