### ISSUE TITLE
Clamtk 5.20 Scheduler doesn't run the scan ?

### ISSUE THREAD

**Issue by gh4wi** [dave-theunsub/clamtk#96]
Scheduled a scan to run at 12:00 , but scheduler did NOT run the scan.
I can run the scan manually OK & it creates a History file.
The scheduler says a daily scan is scheduled, but doesn't run the scan.
What's wrong ?

**Comment by dave-theunsub** [comment]
Hi,

Can you update to a newer version and see if that helps?

https://dave-theunsub.github.io/clamtk/ .   There are pre-packaged versions available there for easy installation.

respectfully
Dave M

**Comment by gh4wi** [comment]
Upgraded to version 5.25 & it solved the problem....THANK YOU !!!
