### ISSUE TITLE
Clamtk v 5.25 missing help icon

### ISSUE THREAD

**Issue by gh4wi** [dave-theunsub/clamtk#97]
Downloaded, installed, & used Clamtk V 5.25 (Ubuntu/Debian *.deb file).
Clamtk V 5.25 is missing the Help Icon found on the Title bar of V 5.20.
Don't know if it was planned to be dropped, or just forgotten.
But I found the Help pages useful & hope they will be added back in.

**Comment by dave-theunsub** [comment]
Closing for now; thanks
