### ISSUE TITLE
clamtk-5.25-1.el7.noarch.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#6ada59de) 

### ISSUE THREAD

**Issue by bobOnGitHub** [dave-theunsub/clamtk#98]
Hi,

Appears to be an issue with rpm signature ( or I'm doing something wrong ) ;

CentOs7

as per readme instructions, your public key imported with ;

rpm --import https://davem.fedorapeople.org/RPM-GPG-KEY-DaveM-10-Sept-2016

verified in list with ;

rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
....
gpg-pubkey-c8128867-4a2af68e --> gpg(Dave Mauroni <dave.nerd@gmail.com>)

rpm downloaded from 
https://bitbucket.org/davem_/clamtk/downloads/clamtk-5.25-1.el7.noarch.rpm
reached via
https://dave-theunsub.github.io/clamtk/

check signature of rpm ;

rpm --checksig clamtk-5.25-1.el7.noarch.rpm
clamtk-5.25-1.el7.noarch.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#6ada59de) 

Bob.

**Comment by dave-theunsub** [comment]
Hi Bob,

Thanks for emailing.  It took me a while, but I think I figured out the issue.  My key was updated and I haven't listed the new one in the link.

If you search pgp.mit.edu for the key it's asking for, you get this:
https://pgp.mit.edu/pks/lookup?search=0x6ada59de&op=index <https://pgp.mit.edu/pks/lookup?search=0x6ada59de&op=index>

That's the updated key, which I need to fix in the documentation.  Anyway, remove the current key (rpm -e gpg-pubkey-c8128867-4a2af68e) and download the key from the link above (click my name or the key number) and save it as something like "davem-updated.asc".  Import (rpm --import davem-updated.asc) and now the verification works.  Sounds confusing...

I even tried an older one to see what happened:

rpm -K clamtk-5.2*
clamtk-5.24-1.el7.noarch.rpm: rsa sha1 (md5) pgp md5 OK
clamtk-5.25-1.el7.noarch.rpm: rsa sha1 (md5) pgp md5 OK
clamtk-5.25-1.fc.noarch.rpm: rsa sha1 (md5) pgp md5 OK

I'll update the info.  Thanks Bob, and let me know if you have further questions.

respectfully
Dave M


Jun 20, 2018, 6:55 AM by notifications@github.com:

**Comment by bobOnGitHub** [comment]
Cheers Dave and thanks for the swift response.

Those links not working for me at the moment ("The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later." )

Will try again later and confirm resolved/close issue when done.

Bob.

**Comment by bobOnGitHub** [comment]
Dave,

Couldn't get anything on those pgp.mit.edu links but used your updated instructions on the installation notes and all ok / verified now.

Thanks,

Bob.
